app/Listeners/ApplicationStatusChanged.php, app/Listeners/JobPublished.php, app/Listeners/LogSuccessfulLogin.php, app/Models/JobPoster.php, resources/views/applicant/job_index/index.html.twig, resources/views/applicant/job_post/header.html.twig
Application status now  being logged properly when it is changed, and applications no longer logged as retrieved when the number of submitted applications is shown.
=> Some fixes to audit logs

.env.example, .scrutinizer.yml, Makefile, README.md, docker-compose.yml, etc/nginx/default.conf, etc/nginx/default.template.conf, gen_certs.bat, routes/web.php
To get the new local url `httops://talent.local.ca` working:
1. Merge this branch into your branch
2. In your .env file, change `APP_URL` to `https://talent.local.ca` *and delete* `APPLICANT_DOMAIN` and `MANAGER_DOMAIN`
3. On windows machines, go to your host file at `C:\Windows\System32\Drivers\etc\hosts`. Delete whatever talent-cloud-related entries are already there (you may have accumulated a couple). Add `127.0.0.1    talent.local.ca`. I don't know the apple equivalent to this step.
4. Restart your docker containers.
5. Restart your browser.
=> Modified local env url from tc.gccollab.ca to talent.local.ca

Dockerfile, Makefile
Changing the owner of the /var/www/ directory when creating a Docker image amounts to a no-op. Since the TalentCloud repository gets bind mounted in the container, changing the owner will also affect the Unix host filesystem and render the user unable to write to files under ./. The application, however, needs write access to ./storage.
I've opted to add a Makefile rule which sets the appropriate permissions on the /var/www/storage directory, allowing the PHP-FPM process to write to it. Running `make set-root-perms` after starting the Docker container resolves the issue.
=> Resolve permission issues on /var/www/storage

resources/views/common/head.html.twig, resources/views/layouts/app.blade.php
This has already been done on the live site
=> Remove integrity and crossorigin from analytics tag

resources/views/common/header.html.twig, resources/views/common/home/hero.html.twig, resources/views/manager/job_create/layout.html.twig
The production server is unable to resolve relative paths in Laravel templates for some reason.
=> Remove relative paths from views

database/factories/JobPosterFactory.php, tests/Feature/JobControllerTest.php
Tests were failing randomly because we added a policy to prevent manager accounts from editing a published job poster, and a state wasn't specified within the tests, causing the factory-created job to be published ~50% of the time.
=> Refactor JobControllerTest factory objects to use unpublished state

.env.example, .env.travis, .scrutinizer.yml, .travis.yml, Makefile, app/Providers/AppServiceProvider.php, composer.lock, config/app.php, config/twigbridge.php, docker-compose.yml, package-lock.json, package.json
- Uses `lighthouse-gh-reporter` npm package to generate reports
- Adds browser to Travis for running the tests
- Separate `.env.travis` file with variables that allow tests to run
- Travis runs faster, Docker pulls the `gctcntgc/talentcloud` image rather than building
- Most useful to check if changes affect the accessibility score, other categories are less accurate in a simulated environment
=> Automated Lighthouse testing during Travis-CI build (only PRs)

app/Http/Controllers/ScreeningPlanController.php, package-lock.json, resources/assets/js/app.js, resources/views/manager/components/assessment-summary.html.twig, resources/views/manager/components/screening-plan.html.twig, resources/views/manager/components/skill-assessment-builder.html.twig, resources/views/manager/components/skill-assessment-preview.html.twig, resources/views/manager/screening-plan.html.twig
Skill names were still being accessed as `skill.skill`, but `skill.name` should now be used.
=> Screening Plan Skill Names bugfix

database/factories/JobPosterFactory.php
should fix test fails for "et", "ex", etc
=> Job seeder assigns longer (and more entertaining) job titles

tests/Feature/JobControllerTest.php
Solution grabbed from https://stackoverflow.com/a/49613639
=> Fix failing unit tests comparing titles with html escaped characters

resources/lang/en/manager/applicant_profile.php, resources/lang/fr/manager/applicant_profile.php, resources/views/manager/applicant_profile.html.twig
Resolves #751 
All questions being empty already had a handler since I was there I added a handler for individual profile questions without answers.
=> Empty Applicant Profile Answers Handling for Manager portal

app/Http/Controllers/Admin/JobPosterCrudController.php, database/factories/JobPosterFactory.php, database/seeds/DevSeeder.php, resources/views/vendor/backpack/crud/buttons/full_edit.blade.php, tests/Feature/JobControllerTest.php, tests/Unit/JobPosterTest.php, tests/Unit/Policies/JobPolicyTest.php
Added a link to the admin view for all Job Posters, did a bit of refactoring to the factory/seeder/unit tests.
Also added links from the Applications column to the applicant view for a given Job Poster.
=> Allow admins to edit draft Job Posters

.vscode/settings.json
This needs to be configured differently on different machines.
=> Remove phpcbf executable path from vscode workspace settings

app/CRUD/TalentCloudCrudTrait.php, app/Models/User.php
I think I tracked it down to Backpack's custom static method `isColumnNullable`. Even though the field in question (email) wasn't editable in the view, it was still being referenced and throwing an error. I added a custom trait that extends the one provided by Backpack and added a `citext` mapping to it.
This should also allow us to override more mappings in the future, although we have to be mindful of maintaining this specific method ourselves.
See [this block of code](https://github.com/Laravel-Backpack/CRUD/blob/b5ca85f12f8f3b5a9e005cc31e820dc34ac8a2ed/src/CrudTrait.php#L54-L73) for the original implementation.
=> Add custom crud trait that overrides isColumnNullable

.vscode/settings.json
The extension being used for PHPCBF seems to require an absolute path to the ruleset file. For now it makes more sense to store it in the user settings.
=> Remove phpcbf ruleset from vscode settings

app/Models/JobPoster.php
Apparently Backpack requires fields its updating to be part of the fillable array. Note: it will fail to update the field, while returning a "Update Successful" message, if this is not the case. 
Part of issue #812.
https://github.com/Laravel-Backpack/CRUD/issues/346
=> Added published to 'fillable' array on JobPoster model

resources/views/common/head.html.twig, webpack.mix.js
Relates to #818 
The site CSS file was being queued after about 5 different Javascript files, some of which are external to our server. Moving the CSS file as high as possible should eliminate flashes of unstyled content.
=> Move site stylesheet as high as possible in the head

app/Http/Controllers/Admin/ManagerCrudController.php, app/Http/Controllers/JobController.php, app/Http/ViewComposers/MenuComposer.php, app/Models/Manager.php, app/Policies/JobPolicy.php, resources/lang/en/manager/menu.php, resources/lang/fr/manager/menu.php, resources/views/manager/job_index/layout.html.twig, resources/views/vendor/backpack/base/inc/sidebar_content.blade.php, resources/views/vendor/backpack/crud/buttons/create_job_poster.blade.php, routes/backpack/custom.php, routes/web.php, tests/Feature/JobControllerTest.php
Added a Managers page to the Admin portal, where admins can create a job poster for any manager. Removed the Create Job Poster menu item from the manager portal, and update permissions so Managers can update, but not create, job posters.
Resolves #817
=> Removed Job Poster Creation from Managers

app/Http/Controllers/JobController.php, app/Utilities/HandleNullState.php
Relates to #870 
There was no `use` statement for the Criteria model, causing problems with instantiation. Also had an error pop up with the `handleNullState` utility method so I added an additional logical check and removed the typing from the parameter.
=> Resolve 500 error during admin portal Job Poster creation

resources/lang/en/common/lookup/skill_level.php, resources/lang/fr/common/lookup/skill_level.php
Missing langfile(s) causing issues in the assessment plan. Looks like they were removed for failing a lang unit test comparison, as we never had French translations.
=> Add skill_level langfiles back in

resources/assets/sass/components/common/_forms.scss
Resolves #887 
- Quick fix for labels overlapping for application progress sticky header.
=> set z-index lower than sticky application progress header

resources/assets/js/app.js, resources/views/applicant/application_post/step_01/questions.html.twig
Minor performance gain saving `$(this)` and other jQuery selectors in a variable. If not saved it has to traverse the DOM each time.
=> Hide checkbox icon depending on checkbox checked status

app/Http/Controllers/SkillDeclarationController.php, app/Models/SkillDeclaration.php, tests/Feature/SkillDeclarationControllerTest.php
Relates to #984 
- Some of the documented return types for controller actions are incorrect/too specific
- We had a short period of time where PHP was formatting on save, causing return type hinting to be added to the controller methods based on the documented return types
- In cases where the typehinted return types were mixed or potentially different (in this case, when returning JSON from an ajax call instead of `\Illuminate\Http\Response` objects) PHP dies in a blaze of glory
=> Fix issue with Skill Declaration ajax update

tests/Feature/ReferencesControllerTest.php
- Occasionally names are generated with apostrophes which fail the assertSee check, since the output is HTML encoded as `&#039;`
=> Wrap generated text with HTML entity escaping function

app/Http/Controllers/ApplicationByJobController.php
The front-end Job interface was changed, and we forgot to change how this controller passed job data to match. Fixed now.
=> Ensure data passed to components from controller matches Job interface

resources/assets/sass/components/applicant/job/post/_culture.scss, resources/views/applicant/job_post/culture.html.twig, resources/views/applicant/manager/header.html.twig, resources/views/applicant/profile/header.html.twig, resources/views/manager/profile/header.html.twig
I just found it annoying.
Also resolves #978 across all views.
- Before
- After
=> Cleanup Team Culture formatting on Job Poster

app/Http/Controllers/JobController.php, app/Models/JobPoster.php, app/Models/JobPosterTranslation.php, database/migrations/2019_06_18_145201_remove_hire_impact_from_job_posters.php, database/migrations/2019_06_18_145336_rename_impact_to_hire_impact_job_posters.php, resources/assets/js/api/job.test.ts, resources/views/applicant/job_post/impact.html.twig, resources/views/manager/job_create/form.html.twig, tests/Feature/JobControllerTest.php
Deleted new hire_impact field, then renamed impact to hire_impact. Now hire_impact will be used in all instances instead of impact, making display of old jobs in new views easier.
=> Changed new impact field so old jobs will be compatible with new views and job builder

resources/assets/js/models/localizedConstants.tsx
Fixes typo on translation key for Prince Edward Island.
=> fixes Prince Edward Island translation key typo

resources/assets/js/components/AssessmentPlan/AssessmentPlanSkill.tsx, resources/assets/js/components/AssessmentPlan/AssessmentPlanTable.tsx, resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx, resources/assets/js/components/AssessmentPlan/RatingGuideClipboard.tsx, resources/assets/js/store/Job/jobSelectorComplex.ts
This should also stop AssessmentPlanTable from occasionally throwing an error when skills haven't loaded yet.
=> Filter nulls out of arrays in a type-safe way

resources/views/applicant/application_index/application.html.twig, resources/views/common/application/view/view_sidebar.html.twig
Resolves #872
- Adds `View Application` button back to all sections, regardless of the status of the application
- Removes the `Submit` option from the application preview sidebar, as there was no corresponding template to render anyway
=> Add View Application button to completed and expired draft applications

app/Models/JobPoster.php, app/Services/WhichPortal.php, tests/Unit/WhichPortalTest.php
After recent changes, WhichPortal was falsely determining that the Manager homepage was the applicant portal (because there was no trailing backslash on the url).
=> Fix bug in WhichPortal, and add regression tests

resources/assets/js/components/JobBuilderImpact/JobBuilderImpact.tsx, resources/assets/js/components/JobBuilderWorkEnv/WorkEnvForm.tsx, resources/assets/js/components/JobDetails/JobDetails.tsx, resources/assets/js/components/Modal.tsx
Couple things were happening with the modals:
1. The render method had a createPortal call that was looking for `parentElement || document.body` to get around typescript issues with a possibly null `parentElement`. This caused the Modal markup to be added twice, once to the `<body>` tag and again wherever it was supposed to live once the DOM settled.
2. Conditionally rendering the Modal with `isModalVisible` would remove it from the DOM on a state change, preventing the `useEffect` call that would release the body scrolling from running.
I also removed the `data-c-dialog-id` attributes to avoid collisions with Clone's Javascript file.
Can test with storybook. Modals should no longer lock scrolling after being closed, and there shouldn't be duplicate markup underneath the actual story.
=> Fix Modal rendering/scrolling issues

.storybook/config.ts
The default tag to render out translated text is `<span>`, causing extra markup to be added to translated components in storybook
=> Set the intl text component to React.Fragment in storybook stories

.travis.yml, package.json, tests/Unit/Helpers/HelperTest.php
Firefox seems to have intermittent issues with selectors on the page that Chrome does not. Removing for now.
=> Remove Firefox from the testcafe-ci script

database/factories/JobPosterFactory.php
Our PT day end to UTC function returns 6:59:59 UTC for the close time for the Job Poster. If the test suite runs around 6:58:00 UTC the close time is in the future, which sets a 'published' status instead of a 'closed' status. I just moved the factory day to be a couple days in the past instead of one.
=> Fix intermittent failing Job Poster status test

resources/assets/js/components/Modal.tsx
React.cloneElement was causing errors when using client-side routing
=> Simplified how modal buttons are aligned

resources/assets/js/components/JobBuilderIntro/JobBuilderIntro.tsx, resources/assets/js/components/JobDetails/JobDetailsPage.tsx
The details step was missing the internal navigation that the other steps already have.
=> Use client-side routing to navigate from JPB Details page

resources/assets/js/components/JobReview/JobReview.tsx, resources/assets/js/models/types.ts, resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobReview/JobReview.json, resources/assets/js/translations/locales/defaultMessages.json, resources/assets/js/translations/locales/fr.json
Resolves #1334.
- If a manager has never edited their profile yet, its possible for the translated portions to come back undefined from the server. This is now accommodated by frontend code.
=> Accommodate possibility of undefined manager translations from server

resources/assets/js/components/JobBuilderImpact/JobBuilderImpact.tsx, resources/assets/js/components/JobBuilderSkills/JobBuilderSkills.tsx, resources/assets/js/components/JobBuilderWorkEnv/WorkEnvModal.tsx, resources/assets/js/components/JobDetails/JobDetails.tsx, resources/assets/js/components/JobReview/JobReview.tsx, resources/assets/js/components/JobTasks/JobTasks.tsx
Fixes a few strings that were being spit out without `<p>` tags, as well as adds null states for skills on both the modal and review steps.
=> Copy / Null State Fixes

app/Http/Controllers/Admin/JobPosterCrudController.php, app/Models/JobPoster.php, tests/Unit/JobPosterTest.php
Resolves #1355.
- This is a very minimal PR. It doesn't stop an admin from publishing a Job in an incomplete state (missing open dates, close dates, etc). That can be added in a separate PR.
=> Avoid null exceptions when trying to publish poster.

resources/views/common/redux.html.twig, resources/views/manager/job-builder-root.html.twig
Job Poster Builder and Assessment Plan were missing hero section headings
=> Update React root templates to include proper headings

resources/assets/sass/components/applicant/job/post/_apply.scss, resources/assets/sass/components/applicant/job/post/_header.scss, resources/lang/en/applicant/job_post.php, resources/lang/fr/applicant/job_post.php, resources/views/applicant/jpb_job_post/culture.html.twig
Resolves #1390  
- Removed the duplicate "Team culture" section from modal.
- Changed close button from "Okay" to "Close",
- Responsive style changes to job poster.
=> Remove "Team Culture" section from job poster modal

jest.config.js
console.warn node_modules/@testing-library/react/cleanup-after-each.js:1
The module `@testing-library/react/cleanup-after-each` has been deprecated and no longer does anything (it is not needed). You no longer need to import this module and can safely remove any import or configuration which imports this module
=> removes deprecated module from jest config

resources/views/applicant/jpb_job_post/culture.html.twig, resources/views/common/modals/skills_need_help.html.twig
Clone's latest js is throwing an error when the modal is opened if no elements contain the `data-c-dialog-focus` attribute, adding to alleviate for now.
=> Add data-c-dialog-focus attribute to clone modal

resources/views/common/head.html.twig
Resolves error: ```Failed to find a valid digest in the 'integrity' attribute for resource 'https://html2canvas.hertzen.com/dist/html2canvas.js' ... The resource has been blocked.```
=> Generate new SRI hash for html2canvas

resources/assets/js/components/JobBuilder/JobBuilderStep.tsx, resources/assets/js/components/Modal.tsx
Resolves #1582 
- Set the modal to always overflow if the height exceeds the view-port height. 
- Also, removed error icon flash from the JPB progress tracker.
=> Bugfix - Set Modal to always overflow 

resources/views/auth/passwords/reset.html.twig
Resolves #1719
- During a template change the password confirmation `name` attribute was changed from `password_confirmation` to `password-confirmation`. Laravel core expects the former so it wasn't used during the `confirmed` validation check.
=> Fix issue with password confirmation naming

app/Policies/JobPolicy.php
Resolves #711 
- Job poster can be viewed now only if:
- The job poster `status` is published published.
- If the user is the manager that created the job poster.
- User is an Admin.
=> Bugfix - Authorization viewing published job poster

composer.lock
Turns out tightenco/parental was prevent other deps from being updated (most notably, laravel framework itself), so I just did them all in one fell swoop.
=> Update outdated composer dependencies

resources/lang/en/applicant/faq.php, resources/lang/fr/applicant/faq.php
Done at the request of @Jerryescandon because it's less applicable to applicants.
=> Moves partner section to the manager area of the FAQ

resources/assets/js/components/JobBuilderSkills/JobBuilderSkills.tsx
@laurenoncoffee requested that we remove the skill icon from the skills list on the job poster builder as it wasn't useful. I've also rounded the skill level to a pill to avoid confusion as it looked like a button.
=> Removes skill icon from the skill list on the job poster builder.

app/Http/Controllers/Auth/TwoFactorController.php, resources/views/applicant/profile/about/about.html.twig, resources/views/auth/two_factor.html.twig, routes/web.php
Resolves #1757.
- This will make it easier to use the same Two Factor controller methods in the Manager and Admin portals.
=> Don't reference Applicant in two-factor routes

app/Http/Controllers/Auth/RecoveryCodeController.php, app/Http/Middleware/Google2FA.php, resources/views/auth/use_recovery_code.html.twig, routes/web.php
Resolves #1667 
- First off, thank you Tristan.
- Should return the user to the expected/intended URL, before being asked for 2FA.
- Currently, applicants can only reach GET requests. The site doesn't have any place to create a POST request to cause a 405 (that I could find).
=> Bugfix - 2FA - Returning user to expected url

resources/assets/js/bootstrap.js, resources/assets/js/polyfills.js, webpack.mix.js
Resolves #1797.
- Uses the solution mentioned [here](https://github.com/formatjs/react-intl/issues/1433#issuecomment-541788065).
- Setting the resolve.mainFields property of webpack config to `mainFields: ['browser', 'module', 'main']` fixes the issue. From what I understand, it works because this gets the browser to use already-transpiled versions of dependency modules.
=> Get react-intl 3 working in IE

app/Models/JobPoster.php
Noticed this while setting up a code spell checker.
=> Fix datatype typo on Job Poster model

resources/assets/js/components/JobBuilderSkills/CriteriaForm.tsx
When changing a skill criteria in the Job Poster Builder, specificity in the non-current language would be set to null. This fixes that.
=> JPB - Stop nullifying criteria specificity of other language

composer.lock
- Looks like symfony updated and triggered a bunch of dependabot PR's so I closed them all and opened this one
- Using `composer update "symfony/*"` also updated some other packages, so I assume they're related. The [composer docs](https://getcomposer.org/doc/03-cli.md#update-u) mention the wildcard approach.
=> Update symfony packages to 4.3.6

resources/assets/js/components/ProgressTracker/ProgressTrackerItem.tsx
- Quick bug-fix. Want to utilize client-side routing for the reverse clickable links on the progress tracker.
=> Bugfix - Use client-side routing for reverse clickable links.

app/Http/Controllers/Api/JobApiController.php
- Jobs created through the JPB don't set a required property (`job_term_id`) so I set it in the controller rather than integrating it into the React side of the application
=> Cold fix Job Duration not visible on job card

resources/assets/js/components/JobBuilder/Review/JobReview.tsx, resources/assets/js/helpers/router.tsx
=> Use SPA routing when linking from JPB review page to eariler steps.

resources/assets/js/components/JobCard.tsx, resources/assets/js/components/OpenJobAction.tsx, resources/assets/js/models/lookupConstants.ts, resources/assets/js/models/types.ts, resources/assets/js/stories/JobCard.stories.tsx, resources/assets/js/stories/OpenJobAction.stories.tsx
Resolves #1935 
- Created a Job Action Card component for jobs that can be claimed by the current HR adviser. 
- Since there was already a component with the name `JobCard`, I named this `OpenJobAction`. However, I feel it needs a better name.
- The component can be viewed in Storybook under "Open Job Action".
=> Task - open Job Action cards 

app/Http/Controllers/Api/ClaimJobApiController.php, app/Policies/JobPolicy.php, routes/web.php, tests/Feature/ClaimJobApiControllerTest.php
Related to #1894 .
I didn't review PR #2047 before it got merged in, but there are a few minor changes I would have wanted to make, so here they are.
- Add specific JobPolicy permissions for claiming and unclaiming job.
- Changed api from post:claim/post:unclaim to put:claim/delete:claim
=> Some minor changes to claim/unclaim job

resources/lang/en/applicant/faq.php, resources/lang/fr/applicant/faq.php
Adds two new partner departments to the FAQ content.
NOTE: This hasn't touched the database in anyway, just the static content on the one page.
=> Updates partner departments in FAQ

app/Http/Controllers/ApplicantProfileController.php, app/Services/Validation/Rules/LinkedInUrlRule.php, resources/views/applicant/profile/about/about.html.twig
Resolves #1952 
- I found the regex from here: https://stackoverflow.com/a/33760587
- I modified to allow `http` as well. I believe all linkedIn profiles use `.com`, and there is a country code  or `www` for prefix.
- I added the regex pattern to Applicant profile.
=> Bugfix - LinkedIn regex

resources/assets/js/components/JobBuilder/Details/JobDetailsPage.tsx, resources/assets/js/components/JobBuilder/Impact/JobBuilderImpactPage.tsx, resources/assets/js/components/JobBuilder/JobBuilderProgressTracker.tsx, resources/assets/js/components/JobBuilder/JobBuilderStep.tsx, resources/assets/js/components/JobBuilder/RedirectToLastIncompleteStep.tsx, resources/assets/js/components/JobBuilder/Review/JobReviewPage.tsx, resources/assets/js/components/JobBuilder/Tasks/JobTasks.tsx, resources/assets/js/components/JobBuilder/Tasks/JobTasksPage.tsx, resources/assets/js/components/JobBuilder/WorkEnv/JobBuilderWorkEnv.tsx, resources/assets/js/components/JobBuilder/jobBuilderHelpers.ts, resources/assets/js/stories/JobPosterBuilder/RedirectToLastIncompleteStep.stories.tsx, resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobTasks/JobTasks.json, resources/assets/js/translations/locales/defaultMessages.json, resources/assets/js/translations/locales/fr.json
Resolves #2096 
- Changed the name of the constant to make more explicit. 
- `VALID_COUNT` -> `NUM_OF_TASKS`
- Instead of importing the constant into each file using `isJobTasksUntouched`. I removed the argument and called the global value instead. 
- Updated the copy.
=> Bugfix - JPB - Total number of tasks

resources/assets/js/components/JobBuilder/Skills/JobBuilderSkills.tsx, resources/assets/js/translations/locales/fr.json
Resolves #1950 and removes "total" from the essential smileys area in both EN and FR.
=> Removes total from essential skills smiley UI and fixes #1950

app/Http/Controllers/Admin/JobPosterCrudController.php, resources/views/vendor/backpack/crud/buttons/job_poster_link.blade.php
Resolves #1734 
- Currently there is no column in the `job_posters` table that holds the current status. If we want to be able to filter by status we need to add a column in that is linked and updates the value during the lifespan of the job poster. This needs to be an issue on its own. @tristan-orourke 
- I went over this with Chris and from what I understand.. Since the Job Poster Translations are held within a different table this makes it very difficult (maybe not possible) to query the table. A solution is to mimic the setup used in the `skills` table, storing the locale values in JSON format. Again, this should be split up into another issue on it's own. @tristan-orourke 
- For above the page is already responsive.
=> Task - Admin - Job Poster filters

resources/assets/js/app.js
Resolves ?
Can't find the issue for this, it's been happening for a long time.
Each new skill click was adding an extra 'required' asterisk on the radio element, on profiles and job applications.
=> Fix required asterisks on radio elements

.vscode/settings.json
Updated as part of VS Code's new version
=> Use newly added vscode setting for format on save

app/Http/Controllers/Admin/JobPosterCrudController.php, resources/views/vendor/backpack/crud/buttons/create_job_poster.blade.php
Resolves #2492.
- Fixes bug with "Create as Manager" button (on Managers page of Admin portal).
- Also fixes broken "Manager profile" links on the Job Posters page of Admin portal.
=> Fix bugs in admin portal caused by using User id where Manager id was needed

app/Http/Controllers/Admin/JobPosterCrudController.php
Resolves #2671.
- I was only able to reproduce the bug when I left one of the date fields empty. This fix allows the NULL dates to save normally.
=> Accomodate null dates when updating job from admin portal

app/Models/User.php
Resolves #2729.
- I just let Admins be considered to have the role of HrAdvisor. Anything that triggers for Hr Advisors should now trigger for Admins. This is how we deal with Admins using the Manager portal.
=> Let Admins trigger FinishHrRegistration middleware.

app/Http/Controllers/ApplicationByJobController.php, resources/assets/js/app.js, resources/assets/sass/components/common/_forms.scss, resources/views/applicant/application_post_06.html.twig, resources/views/applicant/application_post_complete.html.twig
Resolves #2316 
- I prevented the multiple submits on the front-end and back-end:
- Front-end: disabled the button after submission.
- Back-end: Check if the applications status is equal to `draft` before updating in DB.
=> Bugfix - Prevent multiple applicant submits

package.json
- I want to try seeing if [quarantine mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#quarantine-mode) will stop these randomly breaking tests.
=> Testcafe - Enable quarantine mode

resources/assets/js/components/AssessmentPlan/AssessmentPlanAlert.tsx, resources/assets/js/components/AssessmentPlan/AssessmentPlanSkill.tsx, resources/assets/js/components/AssessmentPlan/AssessmentPlanTable.tsx, resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx, resources/assets/js/components/AssessmentPlan/RatingGuideClipboard.test.ts, resources/assets/js/components/AssessmentPlan/RatingGuideClipboard.tsx, resources/assets/js/components/AssessmentPlan/RatingGuideMissing.tsx, resources/assets/js/components/AssessmentPlan/RatingGuideNarrativeAssessment.tsx, resources/assets/js/components/JobBuilder/Criterion.tsx, resources/assets/js/components/JobBuilder/Details/JobDetails.tsx, resources/assets/js/components/JobBuilder/Intro/IntroForm.tsx, resources/assets/js/components/JobBuilder/JobBasicInfo.tsx, resources/assets/js/components/JobBuilder/Review/JobReview.tsx, resources/assets/js/components/JobBuilder/Skills/CriteriaForm.tsx, resources/assets/js/components/JobBuilder/Skills/JobBuilderSkills.tsx, resources/assets/js/components/JobBuilder/Tasks/JobTasks.tsx, resources/assets/js/components/JobBuilder/WorkEnv/WorkEnvForm.tsx, resources/assets/js/components/JobBuilder/jobBuilderHelpers.ts, resources/assets/js/helpers/localize.ts, resources/assets/js/stories/JobPosterBuilder/Skills.stories.tsx
This adds 3 helper functions:
- Two are for getting a field from a model (eg `city` from a `job`) in the right locale, depending on whether the result may be null or not.
- One function to replace the "get locale from react-intl, throw exception if not en or fr" pattern we have all over the place.
I've tried to replace every instance of getting a localized field with the use of a function (except for cases where we're constructing a new model or using both locales). 
I've only replaced getting locale from react-intl in a few places so far.
- Having all localization go through a couple functions will make it easy to do things like add null checking for everything.
- The type checking on these functions is actually helpful. You should get code-completion options, for only the localizable …
=> Refactor: Always use function to extract localized values from ts objects

app/Http/Controllers/ApplicationByJobController.php, app/Services/Validation/ApplicationValidator.php
Doesn't resolve, but intended to help investigate #2914.
- When submitting an application fails, we tell the user which steps need to be completed. But it would useful for debugging purposes to know exactly why the step was considered incomplete. This will add those details to the log.
=> When application submission fails, log the causes.

.scrutinizer.yml
I noticed a bottleneck with Scrutinizer earlier.
Editing the YAML hierarchy seems to improve the performance.
Before:
After:
=> Edit config for Scrutinizer

app/Http/Controllers/Admin/JobPosterCrudController.php, app/Http/Controllers/Admin/JobSkillLevelCrudController.php, app/Http/Controllers/Admin/TalentStreamCategoryCrudController.php, app/Http/Controllers/Admin/TalentStreamCrudController.php, app/Models/JobPoster.php, app/Models/Lookup/JobSkillLevel.php, app/Models/Lookup/TalentStream.php, app/Models/Lookup/TalentStreamCategory.php, database/migrations/2020_03_16_233228_create_talent_streams.php, database/migrations/2020_03_16_233439_create_talent_stream_categories.php, database/migrations/2020_03_16_233539_create_job_skill_levels.php, database/migrations/2020_03_16_233612_add_stream_details_to_job_posters.php, database/seeds/DatabaseSeeder.php, database/seeds/TalentStreamSeeder.php, resources/views/vendor/backpack/base/inc/sidebar_content.blade.php, routes/backpack/custom.php
Resolves #3163.
- The new lookup tables are left empty. It will be up to admins to populate the Talent Stream, Talent Stream Categories, and Job Skill Level tables.
- However, I've set up a seeder to add some values to the tables for local development.
- These fields can be set in a job poster on the Edit Job Poster page in the admin portal.
=> Add new Talent Stream fields to job poster

app/Http/Controllers/JobController.php, app/Listeners/JobPosterQuestionInitializer.php, app/Providers/EventServiceProvider.php, app/Services/JobPosterDefaultQuestions.php, resources/lang/en/manager/job_create.php, resources/lang/fr/manager/job_create.php
Resolves #3165.
Changes the default questions for Strategic Response jobs. Adds default questions when a job enters the "approved" status, without having to view the Edit Questions page.
- Still missing translations
- The previous process was to save the default questions when a user views the Edit Questions page, if there are no existing questions. This still works the same.
- I've added a listener that adds default questions if the job changes to "approved" status (this is normally when the admin would add questions) and the there are no questions yet.
=> Add strategic response default questions

database/factories/JobPosterFactory.php, database/seeds/DatabaseSeeder.php, database/seeds/StrategicResponseSeeder.php, resources/assets/js/components/StrategicResponse/StrApiTestPage.tsx, resources/assets/js/store/Job/jobSelector.ts, resources/views/applicant/str_api_test.html.twig, routes/web.php, webpack.mix.js
The Strategic Response seeder now creates 100 live jobs in correct department, with correct extra fields.
As a bonus, https://talent.test/en/demo/response/api-test on a local env will load all those jobs with redux+react.
=> Improved Strategic Response seeder & job api test page

app/Http/Controllers/JobController.php, app/Http/Controllers/StrategicResponseController.php, resources/views/applicant/strategic_response_job_post/criteria.html.twig, resources/views/applicant/strategic_response_job_post/header.html.twig, resources/views/applicant/strategic_response_job_post/layout.html.twig, resources/views/applicant/strategic_response_job_post/sidebar.html.twig
Resolves #3272.
Skill levels are still showing up for skill criteria on STR job posters. Remove the skill level, since its no longer part of the application.
Show the actual remote work value.
Order criteria so Hard skills appear before soft skills.
Construct the job title from Stream, Specialty and Level, instead of using actual job title.
On job index page, order streams and specialties alphabetically.
=> Strategic Job Poster cleanup

app/Http/Controllers/ApplicationByJobController.php, app/Providers/ViewComposerServiceProvider.php, resources/views/applicant/strategic_response_application/application_post_01.html.twig, resources/views/applicant/strategic_response_application/application_post_02.html.twig, resources/views/applicant/strategic_response_application/application_post_03.html.twig, resources/views/applicant/strategic_response_application/application_post_04.html.twig, resources/views/applicant/strategic_response_application/application_post_05.html.twig, resources/views/applicant/strategic_response_application/application_post_06.html.twig, resources/views/applicant/strategic_response_application/application_post_complete.html.twig, resources/views/response/header.html.twig, resources/views/response/response-base.html.twig
Use the new STR specific menu, and a header with new banner and no breadcrumbs, on every page of an STR application.
Resolves #3347.
- response/header can be used on other STR pages, potentially.
=> Use a new response/header partial on STR applicatiom

resources/lang/en/response/index.php, resources/lang/fr/response/index.php
Puts "you are an employee" check first in the "apply if" section of the response landing page
=> Changes order of apply criteria on response homepage

etc/sql/create-talent-reserve-db.sql, etc/sql/delete-all-applicant-data.sql
Add sql scripts for creating new talent_reserve db, and wiping applicant data
The following commands should give you a second database called `talent_reserve`, identical to `talentcloud` but without any applicant data:
- `psql -U postgres -d postgres < create-talent-reserve-db.sql`
- `pg_dump -U talentcloud talentcloud > backup.psql`
- `psql -U talentcloud talent_reserve < backup.psql`
- `psql -U talentcloud talent_reserve < delete-all-applicant-data.sql`
=> SQL scripts for creating new database and resetting applicant data

resources/lang/en/response/beta_banner.php, resources/lang/fr/response/beta_banner.php
Changes the alert banner on response pages to be clear about Talent Cloud's status and return timeframe.
=> Changes alert banner messaging

app/Http/Controllers/StrategicResponseController.php, resources/views/response/index/stream.html.twig
Added a couple things in this PR since I was in the neighbourhood
- Restricted the JobPoster query to `live` postings only (root issue)
- Changed the count to reflect the total number of postings within a stream, rather than the number of categories in a stream with postings
- Added an explicit order to the Skill Level query, hopefully resolves the display issue on the live site (postings are in Junior > Mid > Expert order locally)
=> Bugfix - Draft posters display on response page

resources/assets/js/helpers/localize.ts
Added another check on the `localizeField` function in the event `model[field]` is null (which was the case here).
=> Bugfix - Blank JPB review page for new manager accounts

.storybook/config.ts, package-lock.json, package.json
- The removal of `dev: true` throughout package-lock.json seems to be an [ongoing npm bug](https://npm.community/t/package-lock-json-keeps-changing-between-platforms-and-runs/1129/17)
- storybook addon info is apparently deprecated, and was throwing a vulnerability so I removed it for now. The alternative is [storybook addon docs](https://github.com/storybookjs/storybook/blob/next/addons/docs/README.md)
=> Resolve npm audit issues

app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/Auth/RegisterController.php, app/Mail/MicroReferenceMail.php, resources/views/applicant/strategic_response_application/complete.html.twig, resources/views/response/menu.html.twig, routes/web.php
This is in preparation for setting up both sites on the prod server. If the user tries to visit /en/response, which has been the correct url so far, they will be redirected to /response/en, which will connect to the TalentReserve app.
- This will make the response homepage innaccessible in this repo. You can checkout the TalentReserve repo to work on the response homepage.
- This may cause an infinite loop of redirects if you're just hosting this repo locally... not sure what to do about that.
=> Redirect /en/response to /response

resources/views/applicant/job_post/culture.html.twig
Resolves #3233 
- This might be the reason for the 403 error on jobs with id between 1-18. They could be using the old job posters templates (jobs made before the JPB). A route method had a lang file object getting passed as the required parameter instead of the actual job.
=> Bugfix - Old Job Posters 403 error fix  

package-lock.json, package.json
- @formatjs/intl-getcanonicallocales@1.2.4 -> 1.2.6
- @formatjs/intl-pluralrules@2.2.4 -> 2.2.6
- @formatjs/intl-relativetimeformat@5.2.4 -> 5.2.6
=> Update formatjs dependencies

app/Http/Controllers/Api/ApplicationController.php, app/Http/Requests/UpdateJobApplicationBasic.php, app/Http/Resources/JobApplicationBasic.php, app/Models/JobApplication.php, database/migrations/2020_06_10_183107_add_confirmation_fields_to_job_applications_table.php, routes/web.php, tests/Feature/Api/ApplicationControllerTest.php
- Added a couple confirmation fields for the UI: `language_test_confirmed` and `education_requirement_confirmed`
- Added a new Resource class for returning basic Application info... I waffled a bit between using the existing Application Resource but this seemed an easier way to control what fields are returned
- Added a form validator for posted fields, this doesn't check the validity in terms of business rules (i.e. that an applicant is legally able to work in Canada), just that the fields are present and are of the correct data type
=> Add API endpoint for getting and updating basic application info

resources/assets/js/fakeData/fakeApplications.ts, resources/assets/js/fakeData/fakeExperience.ts, resources/assets/js/models/types.ts
- I believe we'll want to setup an endpoint that returns all Experiences for an applicant or application, regardless of experience type. That endpoint will need to add a label to each object to distinguish between different types, which is what the new `Experience` typescript type is meant to represent.
=> Update front-end Application and Experience types, to match backend models better

app/Mail/ScreenCandidatesPrompt.php
It was counting all applications, including non-submitted ones, and was sloppy about localization.
Resolves #4141.
=> Fix bugs in the Screen Candidates prompt email template.

resources/assets/js/helpers/localize.ts
-  https://github.com/GCTC-NTGC/TalentCloud/pull/4009#issuecomment-658195060
=> Bugfix - Allow localizeField to return null or an empty string

resources/assets/js/components/Application/BasicInfo/BasicInfo.tsx, resources/assets/js/components/Application/Experience/Experience.test.tsx, resources/assets/js/components/Application/Experience/Experience.tsx, resources/assets/js/components/Application/Experience/ExperiencePage.tsx, resources/assets/js/components/Application/Experience/__snapshots__/Experience.test.tsx.snap, resources/assets/js/components/Application/ExperienceModals/AwardExperienceModal.tsx, resources/assets/js/components/Application/ExperienceModals/CommunityExperienceModal.tsx, resources/assets/js/components/Application/ExperienceModals/EducationExperienceModal.tsx, resources/assets/js/components/Application/ExperienceModals/EducationSubform.tsx, resources/assets/js/components/Application/ExperienceModals/PersonalExperienceModal.tsx, resources/assets/js/components/Application/ExperienceModals/WorkExperienceModal.tsx, resources/assets/js/components/Application/applicationMessages.ts, resources/assets/js/stories/Application/Experience.stories.tsx, resources/assets/js/stories/Application/ExperienceModals.stories.tsx
Resolves #4335.
- This affects the Basic Info step, and the Education section of the Experience modals.
- If the education requirements of the job are identical to the default for its classification, they will be presented with appropriate bolding.
- If the education requirements do not match the default, they will be present with correct paragraph formatting but no bolding.
=> Show the job's custom Education requirement in Application steps

database/factories/SkillDeclarationFactory.php
- Previously using `$faker->paragraphs(3, true);` would occasionally generate more than the 100 character max validation limit, causing a test failure
- Unsure if this is responsible for all the failures relating to the skillsComplete step, but I ran this test consecutively for over an hour locally with no failures
=> Bugfix - Intermittent test failures around Skill Declaration description validation

webpack.mix.js
Resolves #4582 
- Uses the solution mentioned here: https://github.com/uuidjs/uuid/issues/516#issuecomment-690080241
- It seems that the default value for `mainFields` works fine.
=> Bugfix - IE11 broken due to webpack resolve config

app/Http/Resources/JobApplication.php, app/Http/Resources/JobApplicationBasic.php, resources/assets/js/api/application.ts, resources/assets/js/components/Application/BasicInfo/BasicInfoPage.tsx, resources/assets/js/fakeData/fakeApplications.ts, resources/assets/js/models/types.ts, resources/assets/js/store/Application/applicationActions.ts, resources/assets/js/store/Application/applicationReducer.ts
Resolves #4659.
The issue was that if you visited the review step, saved, and revisted the Review step, it would be stuck in the loading state.
This was caused by the fact the the matching Applicant object, and therefor the matching User object, disappeared from the redux store. It disappeared because the updateApplication request returns a simplified version of the Application, which does not include the Applicant or User model. This new, basic Application overwrote the previous one and the User object was lost.
For now, I've simply been a bit more explicit about the types returned by the different endpoints, and ensured the result of the updateApplication request doesn't overwrite values in the pre-existing Application in the redux store, if they don't appear in the new Basic …
=> Fix updateApplication overwriting Applicant object in redux store

resources/assets/js/components/JobBuilder/JobBuilderProgressTracker.tsx, resources/assets/js/components/JobBuilder/JobBuilderStep.tsx, resources/assets/js/components/JobBuilder/jobBuilderHooks.ts, resources/assets/js/hooks/jobBuilderHooks.ts, resources/assets/js/store/Department/deptSelector.ts
Resolves #4613.
- Rewrites data fetching functions to hooks, modeled after the more recent applicationHooks. 
- Avoids re-fetching job, tasks and criteria when navigating between steps of Job Poster Builder.
- Allows the links in progress bar to be clicked even while data is updating, as long as they've previously been visited.
=> Avoid extra data fetches in JPB and improve navigation between steps

.github/workflows/tests.yml
Though the Github Action tests passed in their original PR (#4814) the phpunit tests have been failing on other branches. The cause is an error that occurs when using chmod on the vendor folder. This PR is an attempt to fix the problem.
=> Fix chmod error stopping phpunit tests from running

routes/web.php
Resolves #4092 
- Fixes 405 status code that appears when trying to create a job as a manager via the backpack admin.
=> Bugfix - Update route admin/jobs/create/as-manager

.storybook/main.ts, .storybook/preview-head.html, .storybook/webpack.config.js
- Removes [react-docgen-typescript-loader](https://github.com/strothj/react-docgen-typescript-loader). Removing this improved performance significantly (build and hot-reload). 
- Explicitly sets the `include` key within `webpack.config.js` to only check within `/js` folder.
- Sets the `stories` value, in the storybook config (`main.ts`), to only parse within the `/js` folder.
Previous build (~1.95 min) and hot-reload(~7 sec) performance:
New build (25 sec) and hot-reload (~2 sec ) performance:
=> Task - Improve storybook build performance

tests/Feature/ApplicantControllerTest.php
- I think will stop the test from failing. There was `classification_id` field being set by adding 1 to another `classification_id` value. So, there was the possibility that the value would be set to a number greater then the highest id value.
=> Bugfix - testUpdateProfile unit test 

resources/assets/js/app.js, resources/lang/en/common/auth/login.php, resources/lang/en/common/auth/register.php, resources/lang/en/common/auth/reset_password.php, resources/lang/en/common/settings.php, resources/lang/fr/common/auth/login.php, resources/lang/fr/common/auth/register.php, resources/lang/fr/common/auth/reset_password.php, resources/lang/fr/common/settings.php, resources/views/auth/login.html.twig, resources/views/auth/passwords/reset.html.twig, resources/views/auth/register.html.twig, resources/views/common/settings.html.twig
Resolves #5160
- I wasn't able to add any text into the button without breaking the styling of the show/hide icons. We could fix this by changing [Clone's password component](https://designwithclone.ca/components/input/password/). However, I think I found another solution using a combo of the `aria-label` and `aria-pressed` attributes. When the user clicks the button, the screen reader will hopefully read, "Show password button pressed".
=> Task - show password button accessibility

app/Http/Controllers/Api/ApplicantSkillsController.php, app/Models/Applicant.php, tests/Feature/Api/ApplicantSkillsControllerTest.php
Resolves #5159 .
- Added a method to Applicant eloquent model which returns a query (not the results) which gets all ExperienceSkills belonging to that applicant.
=> Bugfix - Removing Applicant Skills deletes ExperienceSkills

resources/assets/js/configureStore.ts
This is a QOL change for devs, as the logs don't appear in production anyway.
=> Collapse redux logs that appear in console

resources/views/common/head.html.twig
Updates the integrity attribute for html2canvas to a valid value. The value becomes invalid any time a change is made to the code at https://html2canvas.hertzen.com/dist/html2canvas.js. To avoid having to change this every time that the remote file changes, it may be worth [installing html2canvas via npm](https://html2canvas.hertzen.com/getting-started) instead.
=> Update subresource integrity value for html2canvas

.eslintrc.json, .vscode/settings.json
- Fixes Eslint's auto format on save feature. The eslint-prettier plugin was accidentally removed in a previous [PR](https://github.com/GCTC-NTGC/TalentCloud/pull/5275).
=> Bugfix - Eslint's format on save
