GCTC-NTGC/TalentCloud

public_html/index.html

Merge home styles and CDS stylesheets

Merge home styles

---

public_html/admin/index.php
public_html/admin/js/CreateEditProfileAPI.js
public_html/css/style.css
public_html/index.php
public_html/js/FileUploadAPI.js

Upload button on image upload should be change to say "Save"
"Save" button should be on the right and "Cancel" should be on the left in the Edit profile dialogue.
Remove "clear" button from file upload. I think it is redundant if we have a cancel button.
On step 3 the indicator of where you are in the process changes.

Fixes for the following bugs:

---

public_html/admin/index.php
public_html/css/theme.css
public_html/inc/fip-admin.php
public_html/index.php
public_html/js/DataAPI.js
public_html/js/TalentCloudAPI.js
public_html/tc/sql/16.0.0/insert/gx_base_content_2.sql

- Added more headers
- Added UPDATES with translations of all "..._fr" database entries
- Added separate fip banner for admin side
- Fixed missing resource error caused by Our Team CSS

- Fixed admin side issues caused by headers

---

public_html/admin/index.php
public_html/admin/js/CreateEditProfileAPI.js
public_html/admin/js/CreateJobPosterAPI.js
public_html/admin/js/ManagerEventsAPI.js
public_html/css/style.css
public_html/inc/nav-admin.php
public_html/index.php
public_html/js/FormValidationAPI.js
public_html/js/Messages.js
public_html/js/TalentCloudAPI.js
public_html/js/UserAPI.js
public_html/js/Utilities.js
public_html/tc/.htaccess
public_html/tc/dao/JobPosterDAO.php
public_html/tc/utils/JWTUtils.php

JWT token hash evaluation fix
Admin Home refresh fixed type in adminhome
added logout on token timeout authentication failure
added lookup functions for createEditProfile admin
moved lookups to case switch and common function

Job Poster French city removal fix

---

public_html/css/style.css
public_html/tc/sql/18.0.0/alter/alter_job_poster_application.sql
public_html/tc/sql/18.0.0/content/base_content_dashboard.sql
public_html/tc/sql/18.0.0/create/create_application_status.sql
public_html/tc/sql/18.0.0/create/create_application_status_details.sql
public_html/tc/sql/18.0.0/insert/insert_application_status.sql
public_html/tc/sql/18.0.0/insert/insert_application_status_details.sql

Not really manager profile refactoring... updated CSS for Dashboard and add SQL for application_status tables.

Gb job poster manager profile refactoring

---

public_html/inc/applicant/page-view-job-poster.php
public_html/inc/common/header-nav.php

G2 merge cleanup

---

public_html/inc/applicant/page-manager-profile.php
public_html/js/DataAPI.js
public_html/js/EventsAPI.js
public_html/js/JobPostAPI.js
public_html/js/TalentCloudAPI.js
public_html/tc/sql/22.0.0/insert/base_content.sql

G2 back to job

---

public_html/admin/js/CreateEditProfileAPI.js
public_html/admin/js/CreateJobPosterAPI.js
public_html/inc/applicant/page-applicant-profile.php
public_html/inc/applicant/page-application-form.php
public_html/inc/applicant/partial-applicant-evidence.php
public_html/inc/common/head.php
public_html/js/DashboardAPI.js
public_html/js/FAQAPI.js
public_html/js/JobApplicationAPI.js
public_html/js/JobApplicationPreviewAPI.js
public_html/js/JobPostAPI.js
public_html/js/JobSeekerAPI.js
public_html/js/ManagerProfileAPI.js

Updates analytics code for single page app.

Jb analytics

---

public_html/tc/controller/ProfilePicController.php
public_html/tc/controller/WorkEnvironmentController.php
public_html/tc/services/Authentication.php

@gggrant requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/GCTC-NTGC/TalentCloud/

Scrutinizer Auto-Fixes

---

public_html/inc/applicant/header-fip.php
public_html/inc/applicant/page-home-content.php
public_html/inc/common/faq.php
public_html/js/TalentCloudAPI.js
public_html/tc/sql/24.0.0/insert/base_content_email_faq_app_preview.sql

Qf update static content 20180613

---

public_html/admin/js/CreateJobPosterAPI.js
public_html/inc/applicant/page-view-job-poster.php
public_html/inc/manager/page-create-job-poster.php
public_html/js/JobPostAPI.js
public_html/js/TalentCloudAPI.js
public_html/tc/dao/JobPosterDAO.php
public_html/tc/model/JobPoster.php
public_html/tc/model/JobPosterNonLocalized.php
public_html/tc/services/JobPoster.php
public_html/tc/sql/24.0.0/alter/alter_job_poster_add_noc.sql
public_html/tc/sql/24.0.0/insert/base_content_evidence_and_job_poster.sql

NOC Implemented onto create job poster and job poster. Please review and merge.

Qf add noc to create job poster 20180612

---

public_html/inc/common/partial-applicant-evidence-preview.php
public_html/tc/sql/25.0.0/insert/application_preview.sql

Please peer review this and merge into master.
Note: I am still waiting for more translations to come through from the project team, so this will be the latest update from me for this sprint if I don't get anything else from them.

further updated base content on application preview

---

public_html/css/compiled/app.css
public_html/inc/applicant/header-fip.php
public_html/inc/applicant/page-view-job-poster.php
public_html/inc/common/partial-applicant-evidence-preview.php
public_html/scss/molecules/job-poster-content.scss
public_html/tc/sql/25.0.0/insert/base_content.sql

Jerbo: A maple leaf does not exist within the Font Awesome library, unless if I am missing it.... I used a globe instead... please advise if there is an alternative icon you would like to use for hiring preference in Job Poster.
Grant: Please peer review this and merge to master

Qf static content update 20180628

---

.github/ISSUE_TEMPLATE/task-template.md

Default checklist now describes process of getting a pull request accepted into dev.

Update task template

---

resources/lang/en/applicant/job_post.php
resources/lang/fr/applicant/job_post.php
resources/views/applicant/job_post/culture.html.twig

Translation for Job Poster page

Gobyrne language 1

---

app/Http/ViewComposers/MenuComposer.php
app/Models/User.php
app/Services/Auth/Contracts/JSONGetter.php
app/Services/Auth/Contracts/JSONPoster.php
app/Services/Auth/JSONFetcher.php
app/Services/Auth/JumboJettTokenRefresher.php
app/Services/Auth/JwtKeysFetcher.php
app/Services/Auth/OidConnectGuard.php
app/Services/Auth/RequestTokenParser.php
app/Services/Auth/SessionTokenStorage.php
app/Services/WhichPortal.php
resources/lang/en/applicant/menu.php
resources/lang/en/common/footer.php
resources/lang/en/common/menu.php
resources/lang/en/manager/menu.php
resources/lang/fr/applicant/menu.php
resources/lang/fr/common/footer.php
resources/lang/fr/manager/menu.php

Remove php return types (for more php version compatibility) and remove route() calls from lang files.

Server hotfixes

---

app/Providers/AppServiceProvider.php
routes/web.php

Made all routes and requests, including those by Mcamara\LaravelLocalization package, use HTTPS.

---

README.md

A couple of additional steps and precautions for people setting up a testing environment as well.

Small update included for PHPUnit installation.

---

app/Models/JobPoster.php
resources/lang/en/common/time.php
resources/lang/fr/common/time.php

Here is an alternate solution to PR #482. Feel free to use or discard these changes.

Provide a more accurate timestamp for job application deadlines

---

.env.example
.gitignore
Makefile
README.md
database/db/dumps/create-db-user.sql
database/db/dumps/migration/mysql/mysqldb-dump.sql
database/db/dumps/migration/old/db.sql
database/db/dumps/migration/pgsql/pgsql-tables.sql
docker-compose.yml

To test:
I renamed the DB container to ‘Postgres’, requires a change in .env:
DB_HOST=postgres
Create the DB data volume in Docker:
docker volume create pgdata
NOTE:
Do not use docker-compose down with -v or the data volume will be erased

Database data persists on container restart

---

app/Providers/AppServiceProvider.php
config/app.php

If variable not in .env file, will default to true.

Can stop app from using https by adding FORCE_HTTPS=false to .env

---

.vscode/settings.json
composer.json
ruleset.xml

I saw scrutinizer is complaining about quite a few documentation issues, this should alleviate that if running PHPCS locally on an IDE.

Add updated phpcs ruleset

---

app/Http/Controllers/JobController.php
resources/views/manager/job_create/criteria.html.twig
resources/views/manager/job_create/form.html.twig

Fairly significant rewrite of the skills (criteria) section of the Job Poster form.

WIP: Sort skills alphabetically on the Job Poster form

---

.gitignore

Add .gitkeep file and update .gitignore

---

routes/web.php

The diff is a bit of a mess because of the code formatting.

Clean up routes

---

.github/ISSUE_TEMPLATE/spike-template.md
.github/ISSUE_TEMPLATE/task-template.md

Updated Task template to reflect how we are actually using them. Also created a very basic spike template.

Gobyrne templates

---

.github/ISSUE_TEMPLATE/bug-template.md
.github/ISSUE_TEMPLATE/task-template.md

Addresses updates to definition of done discussed as part of #643

Gobyrne templates 2

---

composer.json

Performance seems slightly better. Tested the application after upgrading.

Upgrade outdated composer packages / add spatie/laravel-backup and filp/whoops

---

resources/views/common/skill.html.twig

Modals don't exist yet, buttons shouldn't either

Comment out buttons that bring up modals to create relatives from skills

---

README.md

Update README Adminer and PHP Extensions

---

.gitignore
.travis.yml
composer.lock
package-lock.json

Plus some slight speed improvements for builds in Travis config.

Start tracking compiled lock files

---

README.md

Now everyone can see the repo status at a glance.

Add badges and useful commands to Readme

---

app/Helpers/Helper.php
config/app.php
config/twigbridge.php
resources/views/applicant/job_index/index.html.twig
resources/views/applicant/job_post/header.html.twig
tests/Unit/Helpers/HelperTest.php

Display Last Full Day to apply on Job Posters

---

app/Http/ViewComposers/MenuComposer.php
resources/views/manager/review_applications.html.twig

Fixes page header and highlights a nav-menu item. Resolves issue #769

UI touch-ups on review applications page

---

app/Models/Skill.php
resources/assets/js/app.js
resources/views/common/skill.html.twig
routes/web.php

After the Skill localization change (stored as json in the database), an ajax response was in a different format, causing display issues on the front end. I did some finagling with Laravel's `toArray()` method to return the correct localization values in the original response format.

Fix skills not displaying properly on application

---

resources/assets/sass/components/applicant/application/index/_index.scss
resources/views/applicant/application_index/application.html.twig

Resolves #741 
- Removed the "Edit Draft" button if application is expired
- If styling needs to be improved let me know!

removed edit button for expired apps

---

resources/lang/en/manager/job_index.php
resources/lang/fr/manager/job_index.php
resources/views/manager/job_index/job.html.twig

Adds a couple of missing localizations.

adds missing l10n to manager jobs index

---

resources/assets/js/app.js
resources/assets/js/components/ApplicationReview/ApplicationReview.tsx
resources/assets/js/components/ApplicationReview/ReviewCategory.tsx
resources/assets/sass/components/manager/applicant-review.scss

- adds copy email button to review applicants view that condenses applicant names and emails into a mail-client friendly list that you can paste into your "to" or "bcc" fields.

Copy Applicant Emails Button

---

app/Http/Controllers/Admin/JobPosterCrudController.php
app/Http/Controllers/Admin/UserCrudController.php
resources/views/vendor/backpack/crud/buttons/profile_edit.blade.php
tests/Feature/AdminPortalTest.php

Admins Should Be Able to Enter Translated Copy in Multiple Locations

---

resources/assets/sass/components/applicant/job/index/_index.scss
resources/lang/en/applicant/job_index.php
resources/lang/fr/applicant/job_index.php
resources/views/applicant/job_index/index.html.twig

Adds a new more comprehensive null state for the job poster index that links to Twitter.
Waiting on french translation confirmation.

Adds new null state for job index.

---

package-lock.json
resources/assets/js/app.js

- Yoni caught a bug when there were multiple applicant buckets - the JS would fail because it wasn't looking for multiples.

Fixes multiple accordions when copying.

---

composer.lock
package-lock.json
resources/assets/js/app.js
resources/assets/sass/app.scss
resources/assets/sass/components/common/_forms.scss
resources/views/auth/login.html.twig
resources/views/auth/passwords/email.html.twig
resources/views/auth/register.html.twig

Resolves #402 
- Removed autocomplete blue background for input, select, and textarea's
- Temporary fix for overlapping labels (won't be needed with new clone-framework)

removed autocomplete background, and fixed overlapping label

---

composer.lock
package-lock.json
resources/assets/js/components/ApplicationReview/ApplicationReviewContainer.tsx
resources/assets/js/components/ApplicationReview/ReviewApplications.tsx
resources/assets/js/components/ApplicationReview/ReviewApplicationsContainer.tsx
resources/assets/js/components/ApplicationReview/ReviewCategory.tsx
resources/lang/en/manager/job_create.php

Resolves #871 .
- Fixes spelling errors / typos in typescript files

Fix speling in typescript files

---

app/Http/Controllers/JobController.php
tests/Feature/JobControllerTest.php

Add default questions to admin-created job posters

---

resources/views/manager/job_create/question.html.twig

Removed `required` attribute on the fields.

Question descriptions not required on Create Job

---

resources/assets/sass/components/applicant/application/post/_citizenship.scss

Added spacing btw error message and text

---

resources/views/manager/job_create/form.html.twig
resources/views/manager/job_create/question.html.twig
resources/views/manager/job_create/task.html.twig

- Gray requested that the required fields can be removed from the job poster builder for smoother workflow

 removed all possible required fields from job poster

---

resources/lang/en/applicant/application_template.php
resources/lang/fr/applicant/application_template.php
resources/views/applicant/application_post/step_01/questions.html.twig

- The language declaration checkbox was missing the french translation.

added french translation for error message

---

app/Http/Controllers/Admin/ManagerCrudController.php
app/Http/Controllers/Admin/UserCrudController.php
resources/views/vendor/backpack/crud/buttons/profile_edit.blade.php

Gray requested the manager profile edit button be moved from Users to Managers.

Move profile edit button to admin manager area

---

app/Http/ViewComposers/SkillComposer.php

Add skills to view composer

---

database/migrations/2019_04_29_010706_add_departments.php
database/migrations/2019_04_29_012129_update_language_requirements.php

Resolves #918 and partially resolves #919.
- DND added to departments list
- Language options updated to include 'Bilingual - Intermediate', 'Bilingual - Advanced' and 'English or French'

Database updates

---

resources/assets/sass/app.scss
resources/lang/en/common/skills.php
resources/lang/fr/common/skills.php

Edits from @gobyrne after deploying.

Copy fixes

---

package-lock.json
resources/assets/sass/components/common/itp.scss
resources/lang/en/common/itp.php
resources/lang/fr/common/itp.php
resources/views/common/static-itp.html.twig

Changes the launch language to fall, fixes height of Meagan's profile photo on mobile devices.

Changes language, fixes photo height on mobile.

---

resources/lang/en/applicant/faq.php
resources/lang/fr/applicant/faq.php

Resolves #885.
- Very exciting.

Update FAQ 'Things to Know' with new copy

---

app/Http/Middleware/FullFrameGuard.php
etc/nginx/default.conf

Bug found while testing #761 .

remove duplicate X-Frame-Options header

---

resources/assets/sass/components/applicant/application/post/_skill-layout.scss
resources/views/common/head.html.twig

Resolves #962 
- Josh and I fixed modal issue (not showing on screen)
- Font-sizes now are matched up 
- added matching hover effect (blue color)

Bugfix - Applicant skills modal

---

resources/assets/sass/components/common/_forms.scss

Resolves # .
- Fixes an error with the form labels in legacy forms.

tweaks legacy form label css

---

resources/assets/js/components/AssessmentPlan/RatingGuideClipboard.test.ts
resources/assets/js/components/AssessmentPlan/RatingGuideClipboard.tsx
resources/assets/js/components/UpdatingInput.tsx

Resolves #987
- Also fixes a bug in clipboard data sort function so data is sorted as specified.

Screening plan/skill descriptions clipboard

---

database/migrations/2019_05_29_174149_update_rating_guide_answer_expected_answer_column.php
package-lock.json
package.json
resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx
resources/assets/js/components/TextArea.tsx
resources/assets/js/components/UpdatingInput.tsx
resources/assets/js/components/UpdatingTextArea.tsx

Screening plan/longer answers

---

app/Http/Controllers/JobController.php
resources/assets/js/api/job.ts
resources/assets/js/api/skill.ts
resources/assets/js/components/ApplicationReview/ApplicationReview.tsx
resources/assets/js/components/ApplicationReview/ReviewApplications.tsx
resources/assets/js/components/ApplicationReview/ReviewApplicationsContainer.tsx
resources/assets/js/components/AssessmentPlan/AssessmentPlan.tsx
resources/assets/js/components/AssessmentPlan/AssessmentPlanContainer.tsx
resources/assets/js/components/AssessmentPlan/AssessmentPlanSkill.tsx
resources/assets/js/components/AssessmentPlan/AssessmentPlanTable.tsx
resources/assets/js/components/AssessmentPlan/RatingGuideAnswer.tsx
resources/assets/js/components/AssessmentPlan/RatingGuideBuilder.tsx
resources/assets/js/components/AssessmentPlan/RatingGuideClipboard.test.ts
resources/assets/js/localizations/en.json
resources/assets/js/localizations/fr.json
resources/assets/js/models/types.ts
resources/assets/js/store/Job/jobReducer.test.ts
resources/assets/js/store/Job/jobSelector.test.ts
resources/assets/js/translations/extractedMessages/resources/assets/js/components/ApplicationReview/ReviewApplications.json
resources/assets/js/translations/locales/defaultMessages.json
resources/assets/js/translations/locales/fr.json
tests/Feature/JobControllerTest.php

Removed nested Skill from the Criteria type, and some redundant english strings from some types containing both localizations..

Changed some of the client-side types, as part of normalization

---

database/factories/JobPosterFactory.php

- Noticed this was missing on my local install after seeding fresh data

Add classification string field to Job Poster factory

---

resources/assets/js/components/ApplicationReview/ApplicationReview.tsx
resources/assets/js/components/ApplicationReview/ApplicationReviewWithNav.tsx

Added data-clone attribute for select element styles on review applicants / applications.

Restore manager select element styles

---

app/Http/Controllers/ApplicationByJobController.php
app/Http/Controllers/ExperienceController.php
app/Models/Degree.php
app/Models/WorkExperience.php
database/migrations/2019_06_11_211530_add_blockcert_url_to_degrees.php
resources/lang/en/common/degree.php
resources/lang/fr/common/degree.php
resources/views/common/degree.html.twig

Resolves #1025.
- Adds optional URL field for blockcert links (per Gray/Val's request).

Add blockcert url field to degrees

---

resources/assets/js/helpers/queries.ts
resources/assets/js/models/localizedConstants.tsx
resources/assets/js/models/lookupConstants.ts

This means Departments, Provinces, security clearances, and language requirements. French translations not added yet.

Add constants for items associated with Job by id

---

resources/views/common/application/view/view_01_about.html.twig

Add missing variable declaration to language_requirement condition

---

package-lock.json
resources/assets/js/components/Forms/Select.tsx

- The span tag needs to stay regardless if its required or not for the way the data-clone structure is setup

Select field error 

---

resources/lang/en/applicant/faq.php
resources/lang/fr/applicant/faq.php

Update department list (FAQ)

---

package-lock.json
resources/assets/js/components/JobBuilderIntro/JobBuilderIntro.tsx
resources/assets/js/components/JobBuilderWorkEnv/JobBuilderWorkEnv.tsx
resources/assets/js/components/JobDetails/JobDetailsPage.tsx

Resolves #1059 .
- added this to the places I could find it.
- heads up that impact didn't seem to have one.

Adds some style to the job loading message on the job poster builder.

---

resources/lang/fr/auth.php
tests/Unit/Lang/BaseTranslationTest.php
tests/Unit/Lang/LangFilesTest.php

- Fixes issue where lang tests were failing for me locally.

Lang tests pass locally

---

package-lock.json
resources/assets/js/components/JobBuilderIntro/IntroForm.tsx
resources/assets/js/components/JobBuilderIntro/JobBuilderIntro.tsx
resources/assets/js/fakeData/fakeDepartments.ts
resources/assets/js/stories/JobPosterBuilder/Intro.stories.tsx

Use departments from server on Job Builder Intro page

---

database/migrations/2019_07_04_123456_add_nrc_to_departments.php

- Includes all current partner departments now.

Adds NRC to departments table

---

database/migrations/2019_06_18_224849_add_opc_to_departments.php
database/migrations/2019_07_04_123456_add_nrc_to_departments.php
database/migrations/2019_07_04_170953_update_department_translations.php

- Resolves migration issue on deploy.

Match departments to live DB / order of migrations

---

.scrutinizer.yml
.travis.yml

Trying to cut down the Travis/Scrutinizer run time, as we seem to be doubling up on a lot of checks across different services.

Update CI configuration to reduce runtime

---

resources/assets/js/components/JobBuilderWorkEnv/WorkEnvForm.tsx

Resolves #1098.
These were  "Citizen facing vs back office" and "Collaborative vs Independent", which were already part of the job model but not shown on the form.

Added 2 missing fields to Work Env form 

---

resources/assets/js/components/ProgressTracker/ProgressTracker.tsx
resources/assets/js/components/ProgressTracker/ProgressTrackerItem.tsx
resources/assets/js/components/ProgressTracker/__snapshots__/ProgressTracker.test.tsx.snap
resources/assets/js/components/ProgressTracker/__snapshots__/ProgressTrackerItem.test.tsx.snap
resources/assets/sass/components/common/_tracker.scss

There was some really wonky stuff going on with the progress tracker, so I fixed it. /shrug

Fixes a visual bug with the progress tracker display.

---

resources/assets/sass/components/manager/profile/_layout.scss
resources/views/manager/profile/about.html.twig
resources/views/manager/profile/culture.html.twig
resources/views/manager/profile/environment.html.twig
resources/views/manager/profile/leadership.html.twig

I finally got around to it! Can you just verify that they're fixed based on our previous discussion? Thanks for reminding me @xander-miller

Fixes alignment of buttons on manager profile.

---

app/Http/Controllers/Admin/DepartmentCrudController.php
app/Http/Controllers/Admin/SkillCrudController.php

Resolves #1251, #1253.
- Allowed orderable on `is_culture` / `is_future` columns (Skills)
- Added `id` column and sorting (Departments / Skills)
- Added filter by classification (Skills)

Admin panel ordering / filtering on Skills, Departments

---

resources/assets/js/components/JobTasks/JobTasks.tsx
resources/assets/sass/components/manager/builder.scss

Fix JPB task markup

---

resources/assets/js/components/JobBuilder/jobBuilderHelpers.ts

Show Work Env step complete when only optional fields are missing

---

resources/assets/js/components/JobTasks/JobTasks.tsx

See https://github.com/jaredpalmer/formik/issues/1158#issuecomment-510868126 for more info.

Replace Formik array helpers with local equivalents

---

package-lock.json

Update critical vulnerability in eslint

---

webpack.mix.js

Bugfix - Added missing SkillsWordCounter js file to build

---

resources/assets/js/components/JobBuilderSkills/JobBuilderSkills.tsx

Bugfix - JPB - Duplicate skills in preview modal

---

app/Http/Controllers/JobController.php
app/Http/Controllers/ManagerProfileController.php
app/Http/ViewComposers/DemoNotificationComposer.php
app/Http/ViewComposers/MenuComposer.php
app/Providers/ViewComposerServiceProvider.php
resources/assets/sass/app.scss
resources/assets/sass/components/common/_notification.scss
resources/lang/en/manager/notification.php
resources/lang/fr/manager/notification.php
resources/views/applicant/static_faq.html.twig
resources/views/manager/job_index.html.twig
resources/views/manager/notification.html.twig
resources/views/manager/profile.html.twig
routes/web.php
tests/Unit/Lang/LangFilesTest.php

Resolves #1221 
- Needs French translations `resources/lang/fr/manager/notification.php`
- Fixed an issue with the menu on the manager portal as well (FAQ was linking to manager profile edit)

Add demo account notification to manager portal

---

app/Http/Controllers/Admin/ManagerCrudController.php
app/Http/Controllers/JobController.php
resources/views/vendor/backpack/crud/buttons/create_job_poster.blade.php
routes/web.php

Restore button on Admin portal that creates a blank Job for a manager.

---

resources/assets/js/components/JobBuilder/jobBuilderHelpers.ts

Resolves #1408 
- Set the maximum amount of tasks to 8.

Bugfix - JPB - Set max amount of tasks to 8

---

app/Models/User.php

Check for admin role during manager level check

---

resources/assets/js/components/JobBuilder/JobBuilderStep.tsx
resources/assets/js/components/JobBuilderIntro/JobBuilderIntro.tsx

- Added missing progress bar to Intro page.

Bugfix - JPB - Added progress bar to Intro page

---

resources/views/vendor/backpack/crud/buttons/profile_edit.blade.php

Edit manager profile button (Admin portal) opens a new tab

---

resources/lang/en/common/itp.php
resources/lang/fr/common/itp.php

Meagan asked for a date change on the ITP static page.

ITP Date change

---

resources/assets/js/components/AssessmentPlan/AssessmentPlanBuilder.tsx
resources/assets/js/components/AssessmentPlan/RatingGuideBuilder.tsx
resources/assets/js/components/AssessmentPlan/RatingGuideQuestion.tsx
resources/assets/js/components/AssessmentPlan/RatingGuideQuestionWithAnswers.tsx
resources/assets/js/components/ErrorToast.tsx
resources/assets/js/components/InfoModal.tsx
resources/assets/js/components/JobBuilderSkills/CriteriaForm.test.ts
resources/assets/js/components/WordCounter/WordCounter.tsx
resources/assets/js/components/WordCounter/WordCounterWrapper.tsx
resources/assets/js/fakeData/fakeJob.ts
resources/assets/js/fakeData/fakeRatingGuideAnswer.ts
resources/assets/js/helpers/router.ts
resources/assets/js/managerRegistration.ts
resources/assets/js/models/app.ts
resources/assets/js/models/localizedConstants.test.ts
resources/assets/js/store/Assessment/assessmentActions.ts
resources/assets/js/store/Assessment/assessmentReducer.test.ts
resources/assets/js/store/Assessment/assessmentSelectorComplex.ts
resources/assets/js/store/AssessmentPlan/assessmentPlanActions.ts
resources/assets/js/store/AssessmentPlanNotification/assessmentPlanNotificationActions.ts
resources/assets/js/store/AssessmentPlanNotification/assessmentPlanNotificationSelectors.ts
resources/assets/js/store/Job/jobActions.test.ts
resources/assets/js/store/Job/jobSelectorComplex.ts
resources/assets/js/store/RatingGuideAnswer/ratingGuideAnswerActions.ts
resources/assets/js/store/RatingGuideAnswer/ratingGuideAnswerSelectors.ts
resources/assets/js/store/RatingGuideQuestion/ratingGuideQuestionActions.ts
resources/assets/js/store/Skill/skillActions.ts
resources/assets/js/store/createAction.ts
resources/assets/js/stories/JobPosterBuilder/Review.stories.tsx
resources/assets/js/stories/WordCounter/WordCounter.stories.tsx

- Since I ran through everything during the react-intl update, I cleaned up a bunch of other files with linting complaints.

Clean up eslint errors

---

routes/web.php

- Bug: Assessment plan file name and location changed. Route pathway still used old pathname.

Update assessment plan template path

---

resources/views/auth/first_visit_manager.html.twig
resources/views/auth/manager_registration_fields.html.twig
resources/views/auth/register_manager.html.twig
tests/Browser/2-critical.testcafe.js

Fix bug where gov email wasn't appearing on First Manager Visit page.

---

app/Exceptions/Handler.php
package-lock.json
resources/assets/js/components/ErrorToast.tsx
resources/assets/js/store/Error/errorReducer.ts
resources/lang/en/errors.php
resources/lang/fr/errors.php

Identical to #1646 except without dev merged in.

Add logging and improve toast message for 419 errors - PR for release branch

---

resources/assets/js/components/JobReview/JobReview.tsx
resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobReview/JobReview.json
resources/assets/js/translations/locales/defaultMessages.json
resources/assets/js/translations/locales/fr.json
resources/lang/en/applicant/job_index.php
resources/lang/fr/applicant/job_index.php
resources/views/manager/builder-08.html.twig

Copy change: 'Average Annual Salary'

---

resources/views/applicant/home.html.twig

Display hire_impact on job preview cards (homepage)

---

resources/assets/js/components/AssessmentPlan/RatingGuideQuestionWithAnswers.tsx

Only show/allow RatingGuideAnswers to saved RatingGuideQuestions.

---

app/Models/BackpackUser.php
composer.json
composer.lock

The tightenco repo was apparently abandoned/moved to calebporzio

Replace tightenco/parental with calebporzio/parental

---

resources/lang/fr/applicant/job_post.php

Add missing translations to job poster

---

app/Exceptions/AdminException.php
app/Exceptions/Handler.php
app/Exceptions/TwoFactorRequiredException.php
app/Http/Kernel.php
app/Http/Middleware/Require2FA.php
resources/lang/en/errors.php
resources/lang/fr/errors.php
resources/views/errors/two_factor_required.html.twig
routes/web.php

Gate applications behind new middleware requireing 2fa to be activated.

---

Dockerfile
docker-compose.yml

Resolves 2FA issues in containerized environment.
- `imagemagick-dev` and `imagemagick` must both be installed.

Add imagemagick package to Dockerfile

---

resources/views/applicant/application_post_03.html.twig
resources/views/applicant/application_post_04.html.twig

- Remove duplicate word counter script.

Hotfix - Remove duplicate word counter script

---

app/Http/Controllers/Admin/TwoFactorCrudController.php
app/Http/Controllers/Auth/RecoveryCodeController.php
app/Http/Controllers/Auth/TwoFactorController.php
app/Http/ViewComposers/TwoFactorComposer.php
resources/views/auth/two_factor.html.twig
resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
resources/views/vendor/backpack/crud/buttons/activate_2fa.blade.php
resources/views/vendor/backpack/crud/buttons/deactivate_2fa.blade.php
resources/views/vendor/backpack/crud/buttons/recovery_codes.blade.php
routes/backpack/custom.php
routes/web.php

Manage 2FA via admin portal

---

composer.lock

Should resolve the "incorrect one time password" error on first visit

Update Google2FA packages

---

app/Http/Controllers/Auth/LoginController.php
app/Http/Controllers/ManagerProfileController.php
resources/lang/en/applicant/manager_profile.php
resources/lang/fr/applicant/manager_profile.php
resources/views/applicant/manager/questions.html.twig
resources/views/auth/login.html.twig

Resolves #1854 
- Also includes commit to fix return home link on login page for managers.

Bugfix - Manager profile copy

---

app/Exceptions/Handler.php

Logging the current url (and method) should make it easier to understand what caused logged errors.

Add more context to logged exceptions

---

resources/assets/js/reliability.js
resources/assets/sass/reliability.scss
resources/views/demos/reliability/index.html.twig
resources/views/demos/reliability/templates/background-info.html.twig
resources/views/demos/reliability/templates/consent.html.twig
resources/views/demos/reliability/templates/dialogs/education.html.twig
resources/views/demos/reliability/templates/dialogs/experience.html.twig
resources/views/demos/reliability/templates/dialogs/legal-name.html.twig
resources/views/demos/reliability/templates/dialogs/recognition.html.twig
resources/views/demos/reliability/templates/dialogs/record.html.twig
resources/views/demos/reliability/templates/dialogs/reference.html.twig
resources/views/demos/reliability/templates/dialogs/residence.html.twig
resources/views/demos/reliability/templates/education.html.twig
resources/views/demos/reliability/templates/experience.html.twig
resources/views/demos/reliability/templates/partials/consent-docs.html.twig
resources/views/demos/reliability/templates/partials/provinces.html.twig
resources/views/demos/reliability/templates/partials/screening.html.twig
resources/views/demos/reliability/templates/records.html.twig
resources/views/demos/reliability/templates/references.html.twig
resources/views/demos/reliability/templates/residence.html.twig
resources/views/demos/reliability/templates/summary.html.twig
routes/web.php
webpack.mix.js

Adds the reliability form demo to TC

Adds reliability demo to Talent Cloud

---

resources/assets/js/components/ApplicationReview/helpers.ts
resources/assets/js/components/JobBuilderWorkEnv/WorkEnvForm.tsx
resources/assets/js/components/JobDetails/JobDetails.tsx
resources/assets/js/components/JobDetails/JobDetailsMessages.tsx
resources/assets/js/models/lookupConstants.ts
tests/Browser/3-builder.testcafe.js

Resolves blocker for Rosita making a job poster.
- Includes some other misc language fixes.
- The classification code is AD, which is the same as AS but for a different department.
- Yeah.

Add new classification code

---

app/Models/HrAdvisor.php
app/Models/User.php
database/factories/UserFactory.php
database/migrations/2019_11_07_180655_add_hr_advisor_to_user_roles.php

HR Portal - Add hr_advisor role and model

---

resources/assets/js/components/ApplicantSkills/SkillsWordCounter.tsx
resources/views/applicant/profile/skills/index.html.twig
resources/views/common/skill.html.twig

Bugfix - Fix word counter when adding new skills. 

---

resources/lang/en/applicant/faq.php
resources/lang/en/manager/job_index.php
resources/lang/en/manager/notification.php
resources/lang/fr/applicant/faq.php
resources/lang/fr/manager/job_index.php
resources/lang/fr/manager/notification.php
resources/views/manager/job_index.html.twig
resources/views/manager/notification.html.twig
routes/web.php

Could use a quick review of the French language changes

Fix manager FAQ notification links

---

composer.lock

- Symfony updated again, closed all the dependabot PR's and opened this one
- Some were tagged with [Security] so this update is somewhat important

[Security] Bulk update symfony packages to 4.3.8

---

package-lock.json

Resolve Jest dependency vulnerability

---

package-lock.json

Fix npm audit vulnerability in jest

---

app/Http/Controllers/ApplicationController.php
app/Models/JobApplication.php
resources/views/common/application/view/view_02_experience.html.twig
resources/views/common/application/view/view_03_essential.html.twig
resources/views/common/application/view/view_04_asset.html.twig

Resolves #1700 
- Created a `isDraft` method which returns bool.
- Now when viewing a job application with `draft` status it should grab data through the Applicant model. Otherwise, it will grab it from a copy of the applicant data (which is currently getting done by Tristan).

Task - viewing application data

---

resources/assets/js/components/JobBuilder/Review/JobReview.tsx
resources/assets/js/translations/extractedMessages/resources/assets/js/components/JobReview/JobReview.json
resources/assets/js/translations/locales/defaultMessages.json
resources/assets/js/translations/locales/fr.json
tests/Browser/3-builder.testcafe.js

Change copy for submit button on JPB Review page

---

resources/assets/js/components/ApplicationReview/ReviewCategory.tsx

Remove lang IDs from Review Applicants

---

app/Http/Controllers/Admin/ManagerCrudController.php
app/Http/Controllers/Auth/FirstVisitController.php
app/Http/Middleware/FinishManagerRegistration.php
resources/views/vendor/backpack/crud/buttons/profile_edit.blade.php

Fix 'Edit Profile' link (Manager page, Admin portal)

---

resources/assets/js/components/ApplicationReview/helpers.ts

Bugfix - Review Applicants - 'Non-Canadian' takes precedence over 'Unqualified'

---

resources/views/applicant/application_index/application.html.twig

Resolves #2121.
- Coldfix, file needs to be copied to prod.

Change formatting of close times on Application index.

---

app/Models/Manager.php
resources/assets/js/components/JobBuilder/Intro/IntroForm.tsx
resources/assets/js/components/JobBuilder/Review/JobReview.tsx
resources/assets/js/fakeData/fakeManager.ts
resources/assets/js/models/types.ts
tests/Feature/ManagerApiControllerTest.php

- Fixes breaking change to dev.
- Updated the Manager name attributes to correspond to react side.

Bugfix - manager name attributes

---

ruleset.xml

Fix breaking change in PHP code standard update

---

resources/views/applicant/profile/about/about.html.twig
resources/views/manager/profile/about.html.twig

Turn off autocomplete on Twitter and Linkedin fields

---

resources/assets/js/translations/locales/fr.json

Copy - JPB - Fix translation

---

app/Http/Controllers/Api/JobPosterKeyTaskController.php
app/Http/Resources/JobPosterKeyTask.php
app/Providers/AppServiceProvider.php
routes/web.php
tests/Feature/JobPosterKeyTaskControllerTest.php

Add JobPosterKeyTask resource

---

package-lock.json
package.json
public/images/icon_english_requirement.svg
public/images/icon_french_requirement.svg
resources/assets/sass/components/applicant/job/post/_header.scss
resources/views/applicant/home.html.twig
resources/views/applicant/job_post/language.html.twig
resources/views/manager/home.html.twig
resources/views/manager/notification.html.twig

Fixes a few bugs with UI:
- demo banner layout
- icons on posters
- french required label

Changes Demo Banner, Icon Color on Posters, Fixes French Input Labels

---

resources/lang/en/applicant/faq.php
resources/lang/fr/applicant/faq.php

Add PSPC to partner departments (FAQ)

---

resources/assets/js/components/AssessmentPlan/AssessmentPlanAlert.tsx
resources/assets/js/components/ErrorToast.tsx
resources/assets/js/components/JobBuilder/Tasks/JobTasks.tsx
resources/views/applicant/static/faq-layout.html.twig
resources/views/applicant/static_faq.html.twig
resources/views/demos/reliability/templates/consent.html.twig
resources/views/manager/temp-demo/builder-06-task-01.html.twig
resources/views/manager/temp-demo/builder-06-task-02.html.twig
resources/views/manager/temp-demo/builder-06-task-03.html.twig
resources/views/manager/temp-demo/builder-06-task-04.html.twig
resources/views/manager/temp-demo/builder-06-task-05.html.twig
resources/views/manager/temp-demo/builder-06-task-06.html.twig
resources/views/manager/temp-demo/builder-06-work-env.html.twig

A project wide search only turned up twig files... so it might be worth double checking components in the js folder... I didn't find anything of consequence.

Fixes clone accordions and removes data-c-heading from triggers

---

resources/views/applicant/application_index.html.twig
resources/views/applicant/application_post_01.html.twig
resources/views/applicant/application_post_02.html.twig
resources/views/applicant/application_post_03.html.twig
resources/views/applicant/application_post_04.html.twig
resources/views/applicant/application_post_05.html.twig
resources/views/applicant/application_post_06.html.twig
resources/views/applicant/application_post_complete.html.twig
resources/views/applicant/application_preview.html.twig
resources/views/applicant/home.html.twig
resources/views/applicant/job_index.html.twig
resources/views/applicant/job_post.html.twig
resources/views/applicant/jpb_job_post.html.twig
resources/views/applicant/manager.html.twig
resources/views/applicant/profile_01_about.html.twig
resources/views/applicant/profile_02_experience.html.twig
resources/views/applicant/profile_03_skills.html.twig
resources/views/applicant/profile_04_references.html.twig
resources/views/applicant/profile_05_portfolio.html.twig
resources/views/applicant/static_credentialing.html.twig
resources/views/applicant/static_faq.html.twig

Mostly a bunch of twigcs fixes, but also changes the banner order (GoC/Feedback) on a couple pages where they were flipped.

Page banner order (Job Application 5/6)

---

resources/views/applicant/home.html.twig
resources/views/auth/register.html.twig
resources/views/manager/home.html.twig

Resolves #1928 
- Also some small fixes on applicant and manager homepage

Bugfix - word collision on register form

---

app/Services/Validation/Rules/SkillDeclarationBelongsToUserRule.php
package-lock.json

Resolves a live bug, users unable to add skills to references / work samples.

Fix validation rule / package-lock

---

.travis.yml
Makefile
package.json
tests/Browser/1-smoke.testcafe.js
tests/Browser/2-critical.testcafe.js
tests/Browser/3-builder.testcafe.js

Shaves ~10 minutes off Travis-CI build time:
- browser and unit tests run simultaneously
- removes default `xdebug` extension and generates code coverage with `phpdbg`

Travis-CI performance improvements

---

app/Http/Controllers/Admin/JobPosterCrudController.php
package-lock.json

Bug - Restore link to Applicant Review

---

tests/Browser/2-critical.testcafe.js

- The 'Applicant Profile - My Skills' browser test was breaking for me on travis. It was passing locally thought. I saw it breaking on #2499 as well so I made this change which seems to fix it.

Testcafe - Applicant Profile - My Skills - Fix breaking test.

---

app/Http/Controllers/ApplicationByJobController.php
resources/views/common/skill.html.twig

Users were not being shown their experience or skills when they viewed a preview of their own draft application. This has been fixed.
Resolves #2542 .

Bugfix - Application - Fix broken preview page

---

resources/assets/js/components/ApplicantSkills/SkillsWordCounter.tsx
resources/assets/js/components/Modal.tsx
resources/assets/js/components/ScrollToTop.tsx

- Modal was overflowing outside screen. Might be caused by a clone update.
- ScrollToTop needed children prop in useEffect dependencies.
- Recursively update wordcounter if new skill button is triggered.

Bugfix - misc bugfixes

---

resources/assets/js/components/CommentForm.tsx
resources/assets/js/components/HRPortal/JobReviewHrPage.tsx
resources/assets/js/components/HRPortal/SummaryHrActivityFeed.tsx
resources/assets/js/components/JobBuilder/Review/JobReview.tsx
resources/assets/js/components/JobBuilder/Review/JobReviewActivityFeed.tsx

- Changed layout so accordion is below the header.
- Expanded the horizontal line to fill width.
- Changed layout of summary page

Styling - Activity feeds

---

app/Http/Controllers/JobSummaryController.php
resources/lang/en/common/lookup/job_status.php
resources/lang/fr/common/lookup/job_status.php
resources/views/hr_advisor/job_summary.html.twig

Localize the Job Status on the Job Summary page.

---

resources/lang/en/hr_advisor/job_summary.php
resources/lang/fr/hr_advisor/job_summary.php
resources/views/hr_advisor/job_summary.html.twig

HR Job Summary - Replace list of applicants with the number of applicants

---

app/Http/Controllers/ApplicationByJobController.php
app/Http/Controllers/ApplicationController.php
resources/assets/js/components/ApplicationReview/ApplicantBucket.tsx
resources/assets/js/components/ApplicationReview/ApplicationReview.tsx
resources/assets/js/components/ApplicationReview/ApplicationReviewRoot.tsx
resources/assets/js/components/ApplicationReview/ApplicationReviewWithNav.tsx
resources/assets/js/components/ApplicationReview/ReviewApplications.tsx
resources/assets/js/components/ApplicationReview/ReviewApplicationsRoot.tsx
resources/assets/js/components/ApplicationReview/ReviewCategory.tsx
resources/assets/js/helpers/routes.ts
resources/assets/js/models/app.ts
resources/assets/sass/components/manager/applicant-review.scss
resources/views/manager/application_post.html.twig
resources/views/manager/review_applications.html.twig

Bugfix - links on HR Applicant review pages direct to applicant portal

---

app/Http/Controllers/JobSummaryController.php
resources/views/hr_advisor/job_summary.html.twig
resources/views/hr_advisor/summary_action_card.html.twig

- Show disabled state on the screening plan action card until it is ready for HR Advisors.

Bugfix - Disable screening plan action card

---

app/Http/Controllers/JobController.php
app/Http/Controllers/JobSummaryController.php
package-lock.json
resources/views/hr_advisor/job_summary.html.twig
routes/web.php

Task - Add Hr preview job route

---

resources/views/hr_advisor/job_index.html.twig

Consistent look across new pages.

HR Index - Edit menu styling

---

app/Http/Controllers/Auth/FirstVisitController.php
app/Http/Middleware/FinishHrRegistration.php

Rerun first visit for HR if department or gov email missing.

---

resources/assets/js/components/Activity.tsx

Activity Component - Fix time format

---

resources/views/auth/manager_registration_fields.html.twig
resources/views/auth/register.html.twig

Bugfix - Retain non-sensitive data after form request fails

---

app/Http/Controllers/ApplicationByJobController.php
app/Http/Controllers/JobController.php
resources/lang/en/applicant/job_post.php
resources/lang/fr/applicant/job_post.php
resources/views/common/application/view/view_layout.html.twig

Resolves #2315 
- Now links to the submitted application preview.
- French copy still needs to be approved.

Bugfix - Applying to already submitted application

---

app/Http/Controllers/ManagerProfileController.php
app/Http/Requests/UpdateManagerProfileRequest.php
resources/views/manager/profile/layout.html.twig

Bugfix - Saving manager profile

---

resources/lang/en/applicant/faq.php
resources/lang/fr/applicant/faq.php

Update partner department list

---

package.json
tests/Browser/1-smoke.testcafe.js
tests/Browser/2-critical.testcafe.js

- Using the `fixture-meta` tag we can choose which test we want to run on travis.

Bugfix - Testcafe - Only run specified tests on travis

---

app/Http/ViewComposers/FooterComposer.php
database/migrations/2019_12_05_221612_add_translations_to_criteria_as_json.php
database/migrations/2019_12_05_224054_add_translations_to_job_poster_questions_as_json.php
database/migrations/2019_12_05_224501_add_translations_to_job_poster_key_tasks_as_json.php
database/migrations/2019_12_06_002957_add_translations_to_team_culture_as_json.php
database/migrations/2019_12_06_005552_add_translations_to_work_environment_as_json.php
database/migrations/2019_12_06_010743_add_translations_to_managers_as_json.php
database/migrations/2019_12_06_012307_add_translations_to_job_posters_as_json.php

Fix errors discovered during deployment.

Fix translation migration columns

---

database/migrations/2019_12_06_010743_add_translations_to_managers_as_json.php
database/migrations/2019_12_06_012307_add_translations_to_job_posters_as_json.php

Final fixes from deployment, for consistency.

Deployment fixes for Manager / Job Poster migrations

---

resources/views/applicant/home.html.twig

When I pointed this out, nobody cared.

Improved logic for holiday message

---

app/Exceptions/Handler.php

Case insensitive routes/URLs

---

app/Http/Kernel.php
resources/views/common/header.html.twig
resources/views/errors/default.html.twig

Bug - Error page templates missing session information

---

app/Models/JobApplication.php
app/Models/JobApplicationVersion.php
database/migrations/2020_02_18_041239_add_version_to_job_applications.php

Resolves #2841.
- Do we want to tag everything v1 now, or later?

Add version to Job Applications

---

app/Http/Controllers/JobController.php
resources/lang/en/validation.php
resources/lang/fr/validation.php
resources/views/manager/job_create/layout.html.twig
resources/views/manager/job_create/question.html.twig

Also flash errors to session when validation fails.
Needs translations on the validation FR langfile

Bugfix - Allow deletion of Job Poster Questions

---

app/Http/Controllers/Admin/JobPosterCrudController.php
app/Models/JobPoster.php
database/migrations/2020_02_24_171803_change_process_number_to_string.php

Bugfix - Change PSC # on Job Posters from integer to string type

---

tests/Feature/AdminPortalTest.php

- Deletes the .csv file generated during unit testing.

Delete applicants .csv file

---

composer.lock

Update symfony packages to 4.4.5

---

resources/assets/js/components/JobBuilder/Review/JobReview.tsx

Bugfix - Fix manager information section of Job Review page

---

resources/lang/en/validation.php
resources/lang/fr/validation.php

Change application step 3 error text to explain duplicate skill bug.

---

resources/assets/js/components/HRPortal/JobIndexHrPage.tsx

Bugfix - Prevent duplicate api requests

---

package-lock.json
package.json

- Storybook required a couple packages to be installed.
- @storybook/theming
- @storybook/addons

Bugfix - Storybook installs 

---

app/Http/Requests/ClassificationCrudRequest.php

Lift requirements on classification keys

---

resources/views/vendor/backpack/base/inc/sidebar_content.blade.php

Bugfix - cleanup unfinished merge

---

app/Models/JobPoster.php
app/Policies/JobPolicy.php
config/app.php
resources/assets/js/components/JobBuilder/JobBuilderStep.tsx

Resolves #3151 
- Assumes the `department->name == "Emergency Response`.

Emergency Response - review applicants policy

---

app/Http/Controllers/HomepageController.php
app/Http/Controllers/JobController.php

Emergency Response - hide job posters from strategic response department

---

resources/lang/fr/applicant/job_post.php
resources/lang/fr/manager/job_create.php

Adds missing translations related to #3159 and #3165.

Add missing french translated for Strategic Response posters

---

resources/assets/js/hooks/useDependenciesDebugger.ts

Add to your component and invoke with `useDependenciesDebugger({ dep1, dep2, ... depn });` to see if any change and cause a rerender

Add hook for debugging dependency array in useEffect

---

resources/assets/sass/reliability.scss
resources/views/demos/reliability/index.html.twig
resources/views/demos/reliability/templates/background-info.html.twig
resources/views/demos/reliability/templates/consent.html.twig
resources/views/demos/reliability/templates/dialogs/education.html.twig
resources/views/demos/reliability/templates/dialogs/experience.html.twig
resources/views/demos/reliability/templates/dialogs/recognition.html.twig
resources/views/demos/reliability/templates/dialogs/reference.html.twig
resources/views/demos/reliability/templates/dialogs/residence.html.twig
resources/views/demos/reliability/templates/education.html.twig
resources/views/demos/reliability/templates/experience.html.twig
resources/views/demos/reliability/templates/records.html.twig
resources/views/demos/reliability/templates/references.html.twig
resources/views/demos/reliability/templates/residence.html.twig
resources/views/demos/reliability/templates/summary.html.twig

Updates to match joshbeveridge.ca/tc-reliability

Updates the reliability form to match the mockup.

---

.github/workflows/heroku.yml

This might automate the current deployment process to Heroku

Add test action for Heroku branch

---

resources/assets/js/components/ApplicantSkills/SkillsWordCounter.tsx

WordCounter - Add delay on update that waits till textarea gets created

---

package-lock.json

Thanks Dependabot.
Before:
found 2495 vulnerabilities (2494 low, 1 moderate) in 1359073 scanned packages
After:
found 1 moderate severity vulnerability in 1161662 scanned packages

Fixes dependency issues

---

app/Http/Controllers/JobSummaryController.php
app/Policies/ApplicationPolicy.php
resources/assets/sass/components/manager/job_index/_index.scss
resources/views/manager/job_index/job.html.twig

Bugfix - strategic response - review applicants policy 

---

resources/views/common/head.html.twig

Resolves #3170 
- Thanks @Khristophor

Strategic Response - prevent search engines from indexing webpage

---

app/Http/ViewComposers/StrategicResponseBannerComposer.php
app/Http/ViewComposers/StrategicResponseMenuComposer.php
app/Providers/ViewComposerServiceProvider.php
resources/lang/en/response/beta_banner.php
resources/lang/en/response/index.php
resources/lang/en/response/menu.php
resources/lang/fr/response/beta_banner.php
resources/lang/fr/response/index.php
resources/lang/fr/response/menu.php
resources/views/applicant/strategic_response_job_post.html.twig
resources/views/applicant/strategic_response_job_post/header.html.twig

Strategic Response - Add banner and menu to all pages

---

resources/assets/js/components/ApplicantSkills/SkillsWordCounter.tsx
resources/assets/js/translations/locales/fr.json

Decrease the word limit and sweet spot for skill word counter.

---

resources/lang/en/manager/job_create.php
resources/lang/fr/manager/job_create.php

Add new default job question about working full time

---

resources/views/applicant/home.html.twig
resources/views/applicant/job_index/index.html.twig
resources/views/applicant/jpb_job_post/apply.html.twig
tests/Browser/1-smoke.testcafe.js

Bugfix - Add fix for broken browser tests

---

package-lock.json
package.json
resources/assets/js/components/JobBuilder/Tasks/JobTasks.tsx

- `nanoid` wasn't transpiling to ES5 causing it to break on ie11. Decided to replace it with `uuid`.

Replace nanoid with uuid

---

app/Http/Controllers/Auth/LoginController.php
app/Http/Controllers/Auth/RegisterController.php

Bugfix - Strategic Response login/logout/register redirect

---

resources/views/response/index/content.html.twig
resources/views/response/index/job-list.html.twig
resources/views/response/menu.html.twig

Comments out all links to the response FAQ until its ready.

---

resources/views/applicant/strategic_response_application/common/skill-view.html.twig

Remove skill level from str application view skill accordions

---

routes/web.php

Redirect /reserve to /response

---

app/Http/Controllers/JobController.php

Job Poster - Sort skills by order they were created (id)

---

app/Http/Controllers/ApplicationByJobController.php
app/Services/Validation/Rules/GovernmentEmailRule.php
app/Services/Validation/StrategicResponseApplicationValidator.php
database/factories/ApplicationFactory.php
resources/assets/sass/components/applicant/application/post/_citizenship.scss
resources/views/applicant/strategic_response_application/step_01/questions.html.twig

Resolves #3393 
- Add front and back end validation.
- @tristan-orourke can you double check the regex works. Here is playground I used with some tests: https://regexr.com/5246k

Task - Response - validate gov email

---

app/Http/Controllers/Api/DepartmentController.php
resources/assets/js/components/StrategicTalentResponse/ResponseScreening/ResponseScreeningPage.tsx
resources/assets/js/models/lookupConstants.ts

Bugfix - Strategic Talent Response not available in JPB

---

app/Http/Controllers/AssessmentPlanController.php
app/Http/Controllers/JobController.php
app/Http/Controllers/JobSummaryController.php
resources/lang/en/hr_advisor/job_index.php
resources/lang/en/manager/assessment_plan.php
resources/lang/en/manager/home.php
resources/lang/en/manager/job_index.php
resources/lang/en/manager/menu.php
resources/lang/fr/hr_advisor/job_index.php
resources/lang/fr/manager/assessment_plan.php
resources/lang/fr/manager/home.php
resources/lang/fr/manager/job_index.php
resources/lang/fr/manager/menu.php
resources/views/hr_advisor/job_index.html.twig
resources/views/manager/assessment_plan.html.twig
resources/views/manager/home.html.twig
resources/views/manager/job_index.html.twig

HR / Manager - Fix page titles

---

composer.lock

Update symfony v4.4.7 -> v4.4.8

---

resources/lang/en/manager/job_create.php
resources/lang/en/response/faq.php
resources/lang/fr/manager/job_create.php
resources/lang/fr/response/faq.php

Remove 'accommodation' default question

---

resources/lang/en/response/faq.php
resources/lang/fr/response/faq.php

Adds an FAQ about account creation and Talent Cloud vs Reserve.

Adds extra question about accounts

---

composer.lock

Update Symfony deps to 1.16.0

---

composer.lock

Update Symfony framework deps to 1.17.0

---

resources/lang/en/common/skills.php
resources/lang/fr/common/skills.php
resources/views/common/skill.html.twig

Resolves #3370 
- Also made a copy fix, removing the required skill level on profile page.

Copy - Skills description placeholder

---

app/Services/Validation/RegistrationValidator.php
resources/assets/js/app.js
resources/lang/en/validation.php
resources/lang/fr/validation.php
resources/views/auth/register.html.twig
tests/Feature/RegisterControllerTest.php

- Needs translation for the lang entry in ` resources/lang/fr/validation.php`

Feature - Basic bot trap

---

app/Http/Controllers/ApplicationByJobController.php
resources/lang/en/response/screening.php
resources/lang/fr/response/screening.php
resources/views/response/screening/header.html.twig
resources/views/response/screening/index.html.twig

#3472 
Fixed up the hardcoded bits in the Twig header, needs French translations to the newly added langfile.

Bugfix - Static Response Screening header

---

resources/assets/js/components/StrategicTalentResponse/ResponseScreening/ApplicantBucket.tsx
resources/assets/sass/components/common/response.scss

Bugfix - Make applicant review page responsive

---

resources/assets/js/components/JobBuilder/JobBuilderRoot.tsx

Fix jpb breadcrumbs on ie11

---

package-lock.json

https://npmjs.com/advisories/1486

Update the http-proxy package

---

app/Http/Controllers/JobController.php
resources/assets/js/components/JobPreview.tsx
resources/lang/en/applicant/job_post.php
resources/lang/fr/applicant/job_post.php
resources/views/applicant/jpb_job_post/header.html.twig

Bugfix - Job's chosen lang null fix

---

resources/lang/en/common/hero.php
resources/lang/fr/applicant/faq.php
resources/lang/fr/common/hero.php

Use the route() helper in lang file instead of hardcoding url

---

app/Http/Controllers/JobController.php
resources/lang/en/manager/job_index.php
resources/lang/fr/manager/job_index.php
resources/views/manager/job_index/job.html.twig

Updates manager job index to change the summary button label and the title link to go to the summary.
Resolves #3867

Updates Manager Job Index Actions

---

resources/views/applicant/home.html.twig

Just a minor aesthetic change to the homepage.

Changes applicant homepage to flag background

---

resources/lang/en/manager/job_index.php
resources/lang/fr/manager/job_index.php
resources/views/manager/job_index/job.html.twig
tests/Browser/3-builder.testcafe.js

Task - Remove '(Preview)' from job title link

---

resources/assets/js/components/JobBuilder/Intro/JobIntroPage.tsx

Bugfix - JPB - Continue in French route

---

app/Http/Controllers/JobSummaryController.php
resources/lang/en/hr_advisor/job_summary.php
resources/lang/fr/hr_advisor/job_summary.php
resources/views/common/job_summary/job_summary.html.twig
resources/views/common/job_summary/side_button.html.twig

Resolves #3875 
- Added a confirmation popup for relinquishing a job as well.

Task - Confirmation modal for Job Poster status transition

---

resources/assets/sass/app.scss
resources/views/applicant/application/09-submit.html.twig
resources/views/applicant/application/action-buttons.html.twig

Does three things:
- removes the form class
- updates the signature font to Georgia
- changes the final action button to green

Honesty Pledge Update

---

etc/scripts/deploy-instructions.txt
etc/scripts/deploy.sh
etc/scripts/deploy_dev_reserve.sh
etc/scripts/deploy_dev_talentcloud.sh
etc/scripts/deploy_reserve.sh
etc/scripts/deploy_talentcloud.sh

Resolves #4059.
- I created a single script that accepts two parameters: the name of the zip file containing new code, and the destination app folder. This will make it easier to maintain, because there's no more duplication of code between different deploy scripts. For convenience, I set up separate scripts for each situation (prod/dev and tc/reserve) that call the main script with appropriate arguments.
- This new script still needs to be tested (on dev), since I don't a working tablet right now.

Update deployment scripts

---

resources/assets/js/components/Application/FinalSubmit/FinalSubmit.tsx
resources/assets/js/components/Input.tsx
resources/assets/js/stories/Application/FinalSubmit.stories.tsx
resources/views/applicant/application/09-submit.html.twig

Resolves #2893 
- The component can be viewed in storybook under Final Submit.

Application Timeline - Final submission

---

resources/lang/en/applicant/faq.php
resources/lang/fr/applicant/faq.php

Remove HC and DND from partner department list (FAQ)

---

app/Http/Controllers/Api/AwardRecipientTypeController.php
app/Http/Controllers/Api/AwardRecognitionTypeController.php
app/Http/Controllers/Api/EducationStatusController.php
app/Http/Controllers/Api/EducationTypeController.php
routes/web.php
tests/Feature/Api/AwardRecipientTypeControllerTest.php
tests/Feature/Api/AwardRecognitionTypeControllerTest.php
tests/Feature/Api/EducationStatusControllerTest.php
tests/Feature/Api/EducationTypeControllerTest.php

Add API endpoints for Application Constants

---

resources/assets/js/api/awardRecipientType.ts
resources/assets/js/api/awardRecognitionType.ts
resources/assets/js/api/educationStatus.ts
resources/assets/js/api/educationType.ts
resources/assets/js/models/types.ts
resources/assets/js/store/AwardRecipientType/awardRecipientTypeActions.ts
resources/assets/js/store/AwardRecipientType/awardRecipientTypeReducer.test.ts
resources/assets/js/store/AwardRecipientType/awardRecipientTypeReducer.ts
resources/assets/js/store/AwardRecipientType/awardRecipientTypeSelector.ts
resources/assets/js/store/AwardRecognitionType/awardRecognitionTypeActions.ts
resources/assets/js/store/AwardRecognitionType/awardRecognitionTypeReducer.test.ts
resources/assets/js/store/AwardRecognitionType/awardRecognitionTypeReducer.ts
resources/assets/js/store/AwardRecognitionType/awardRecognitionTypeSelector.ts
resources/assets/js/store/EducationStatus/educationStatusActions.ts
resources/assets/js/store/EducationStatus/educationStatusReducer.test.ts
resources/assets/js/store/EducationStatus/educationStatusReducer.ts
resources/assets/js/store/EducationStatus/educationStatusSelector.ts
resources/assets/js/store/EducationType/educationTypeActions.ts
resources/assets/js/store/EducationType/educationTypeReducer.test.ts
resources/assets/js/store/EducationType/educationTypeReducer.ts
resources/assets/js/store/EducationType/educationTypeSelector.ts
resources/assets/js/store/store.ts

Add application constants to redux store

---

resources/assets/js/components/Application/ExperienceModals/SkillSubform.tsx
resources/assets/js/components/Form/CheckboxGroupField.tsx
resources/assets/js/components/JobBuilder/WorkEnv/JobWorkEnv.tsx
resources/assets/js/stories/CheckboxGroupField.stories.tsx

- Fixes duplicate id's issue, on Experience Page (skills forms), preventing the `<fieldsets>` being focusable.

Bugfix - CheckboxGroupField focusable

---

resources/views/common/head.html.twig

- Again. Trying a different generator.

Fix subresource integrity for html2canvas

---

database/migrations/2020_10_01_180409_copy_degrees_and_courses_to_experiences_education.php
database/migrations/2020_10_01_180733_copy_work_experiences_to_experiences_work.php

Resolves #4409.
Only copies data, no changes to the existing tables.

Copy course / degree / work experience data to new models

---

app/Jobs/ProcessJobStatusTransitions.php

Fix comment typo

---

README-local.md

- README for new members of the team to install from scratch using macOS

Update local setup instructions

---

etc/scripts/deploy.sh
routes/web.php

- To test, use the command `php artisan route:trans:cache` to cache routes, and `php artisan route:clear` to clear caching
- Locally I see a ~70 - 80 ms reduction in boot time
Before:
After:

Enable route caching

---

resources/assets/js/components/AssessmentPlan/RatingGuideNarrativeAssessment.tsx
resources/assets/js/components/AssessmentPlan/RatingGuideQuestion.tsx

Add missing p tags to Ratings Guide Builder

---

resources/assets/js/translations/locales/fr.json

Update Job Builder french string for required skill

---

resources/assets/js/components/JobBuilder/Skills/JobSkills.tsx

Bugfix - French text wrapping on Criteria name

---

resources/assets/js/translations/locales/fr.json

Fix french translation jobBuilder.review.months

---

package-lock.json
package.json
resources/assets/js/store/Assessment/assessmentSelector.ts
resources/assets/js/store/Assessment/assessmentSelectorComplex.ts
resources/assets/js/store/Job/jobSelectorComplex.ts
resources/assets/js/store/RatingGuideAnswer/ratingGuideAnswerSelectors.ts
resources/assets/js/store/RatingGuideQuestion/ratingGuideQuestionSelectors.ts

Update re-reselect from 3.4.0 to 4.0.0

---

resources/assets/js/managerRegistration.ts

Update manager registration government email value logic

---

app/Http/Resources/JobPoster.php
resources/assets/js/components/HRPortal/JobIndexHrPage.tsx
resources/assets/js/components/JobBuilder/WorkEnv/__snapshots__/JobWorkEnv.test.tsx.snap
resources/assets/js/components/JobCard.tsx
resources/assets/js/fakeData/fakeJob.ts
resources/assets/js/models/jobUtil.ts
resources/assets/js/models/types.ts

Add number of applicants to HR Job Index cards

---

database/seeds/DevSeeder.php

Update seed data for jobs

---

app/Http/Controllers/Admin/DepartmentCrudController.php
app/Http/Controllers/FaqController.php
app/Models/Lookup/Department.php
database/migrations/2020_10_26_230143_add_is_partner_is_host_to_departments_table.php
database/migrations/2020_10_27_164030_add_reorder_to_departments_table.php
etc/scripts/deploy-instructions.txt
resources/lang/en/applicant/faq.php
resources/lang/fr/applicant/faq.php
resources/views/applicant/static/faq-layout.html.twig

Add partner, host fields to Department

---

resources/assets/js/components/Application/ProgressBar/ProgressBar.tsx
resources/assets/js/components/Application/ProgressBar/progressHelpers.ts
resources/assets/js/models/lookupConstants.ts
resources/assets/js/stories/Application/ProgressBar.stories.tsx
resources/assets/sass/components/applicant/application/progress-bar.scss

- The loading state was only icon which prevented the user from clicking on it to try and reach another step. This 
removes the loading state and adds a blinking animation instead.

Replace loading state icon with blinking animation

---

resources/assets/js/components/Application/Skills/Skills.tsx

Bugfix - Application - Saving skill justification

---

app/Http/Controllers/Api/ExperienceSkillsController.php
app/Models/ExperienceSkill.php
database/migrations/2020_11_16_235531_add_deleted_at_column_to_experience_skills.php
resources/assets/js/components/Application/Experience/ExperiencePage.tsx
tests/Feature/Api/ExperienceSkillsControllerTest.php
tests/Unit/JobApplicationTest.php

Task - Experience skills bugfix + add soft deletes task

---

app/Http/Controllers/JobController.php

Resolves #3105
Same solution used, to disable Clone JavaScript on view, as the following commits:
- https://github.com/GCTC-NTGC/TalentCloud/commit/2fd74614f958431fdd56eb1f3c51102612b08a43
- https://github.com/GCTC-NTGC/TalentCloud/commit/2c6c0711a62b3cf25f56807b1522b28bae953fc7

Fix HR Portal Completed Jobs accordion

---

resources/assets/js/components/Application/Skills/Skills.tsx

Timeline - Only make a request to update the skill if the justification has changed

---

app/Http/Controllers/JobController.php

Fix incorrectly referenced variables

---

app/Http/Controllers/ApplicationController.php
resources/views/applicant/application_index/index.html.twig

Update Application index to lazy eager load status

---

app/Helpers/Helper.php
app/Http/Controllers/Admin/JobPosterCrudController.php

Fix Admin Job Poster date save

---

package-lock.json
package.json
resources/assets/js/polyfills.js

Install and add intl-locale polyfill for new ie11 breaking changes

---

app/Models/Applicant.php
app/Models/Skill.php
database/migrations/2020_12_03_151728_create_applicants_skills_table.php
database/seeds/DevSeeder.php

Resolves #4846.
- Creates a many-to-many relationship between the Applicant model and the Skill model.
- Adds a uniqueness constraint ensuring an applicant cannot have the same skill multiple times.

Create relationship between Applicant and Skill

---

app/Http/Controllers/Api/ApplicationReviewController.php
app/Http/Requests/BatchUpdateApplicationReview.php
app/Policies/ApplicationReviewPolicy.php
app/Policies/JobPolicy.php
app/Providers/AuthServiceProvider.php
database/factories/ApplicationReviewFactory.php
routes/web.php
tests/Feature/Api/ApplicationReviewControllerTest.php

Task - Bulk Update Application Review endpoint

---

resources/assets/js/components/ApplicantProfile/ProfileExperience.tsx
resources/assets/js/components/Application/ExperienceAccordions/ExperienceAccordionCommon.tsx
resources/assets/js/components/Application/ExperienceAccordions/ExperienceAwardAccordion.tsx
resources/assets/js/components/Application/ExperienceAccordions/ExperienceCommunityAccordion.tsx
resources/assets/js/components/Application/ExperienceAccordions/ExperienceEducationAccordion.tsx
resources/assets/js/components/Application/ExperienceAccordions/ExperiencePersonalAccordion.tsx
resources/assets/js/components/Application/ExperienceAccordions/ExperienceWorkAccordion.tsx
resources/assets/js/helpers/forms.ts
resources/assets/js/helpers/router.tsx

Resolves #4863.
- Thanks to @yonikid15 for helping out.

Task - Allow URI fragment on Profile Experience page to open specific experience modal

---

.github/workflows/tests.yml

Replace MilesChou/composer-action with php-actions/composer.
Resolves #5114.

Update GitHub action for installing PHP dependencies

---

app/Http/Controllers/Api/ApplicantSkillsController.php
app/Http/Requests/UpdateApplicantSkills.php
routes/web.php
tests/Feature/Api/ApplicantSkillsControllerTest.php

Add API endpoint for Applicant Skills

---

resources/assets/js/components/H2Components/Accordion.tsx
resources/assets/js/components/H2Components/Dialog.tsx

- Fixes error caused when spreading all props, by only spread the remaining props of the component.

Bugfix - H2 react components

---

app/Http/Requests/UpdateApplicantProfile.php
tests/Feature/ApplicantControllerTest.php

Bugfix - Test update profile unit test

---

tests/Feature/Api/ApplicantSkillsControllerTest.php

PHP Unit test occasionally fails with the following:

Bugfix - test get applicant skills unit test

---

resources/assets/js/components/H2Components/Accordion.tsx
resources/assets/js/components/H2Components/Alert.tsx
resources/assets/js/components/H2Components/Dialog.tsx
resources/assets/js/components/H2Components/utils.ts
resources/assets/js/stories/H2Components/Alert.stories.tsx
resources/assets/js/stories/H2Components/Dialog.stories.tsx
resources/assets/js/stories/H2Components/utils.ts

- Creating this in preparation for a new ErrorToast component
- Also fix some bugs in Accordion and Dialog components, left from a recent H2 update.
- Alert component uses H2 styling, but not scripts for interaction. The parent component will have to manage its visibility and click events. The H2 script, which removed the element entirely from the DOM, caused React errors.

Create H2 Alert component with stories

---

resources/assets/js/components/FindSkillsModal.tsx
resources/assets/js/fakeData/fakeSkillCategories.ts
resources/assets/js/models/types.ts

Code is commented out instead of deleted becuase we want to add description to backend model and then restore this.

Temporarily remove description from client-side SkillCategory

---

resources/views/applicant/application/application-header.html.twig
resources/views/applicant/application/congrats.html.twig
resources/views/applicant/application_post/complete.html.twig
resources/views/manager/builder-01.html.twig
resources/views/manager/builder-06.html.twig

Fix application timeline broken links

---

resources/assets/js/components/Application/Skills/Skills.tsx

Fix text that overlaps caret on accordion

---

resources/views/applicant/application/congrats.html.twig
resources/views/layouts/base-test.html.twig
resources/views/layouts/base.html.twig

Add goc, alert banners for application congrats view

---

resources/assets/js/components/ApplicantProfile/Skills/List.tsx

Add message for no skills in sort by group

---

resources/assets/js/components/Application/Experience/Experience.tsx
resources/assets/js/components/Application/Review/ApplicationPreview.tsx
resources/assets/js/components/Application/Skills/Skills.tsx
resources/assets/js/components/Application/applicationMessages.ts
resources/assets/js/components/Application/helpers.ts

Resolves #5375.
Stops Soft skills from appearing anywhere in the application (Skills step, or skill checkboxes on experience step), except for the "These skills will be evaluated later" message, which has been added to the Skills step as well.

Bugfix - Don't show Soft skills on Application
